// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-service.proto

package com.ortiz.grpc.services;

public final class DataServiceOuterClass {
  private DataServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_GetPersonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_GetPersonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_Phone_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_Phone_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_GetPhoneRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_GetPhoneRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022data-service.proto\022\010services\032\036google/p" +
      "rotobuf/wrappers.proto\"r\n\020GetPersonReque" +
      "st\022.\n\010tenantId\030\001 \001(\0132\034.google.protobuf.S" +
      "tringValue\022.\n\010personId\030\002 \001(\0132\034.google.pr" +
      "otobuf.StringValue\"\346\001\n\005Phone\022(\n\002id\030\001 \001(\013" +
      "2\034.google.protobuf.StringValue\022(\n\003ddi\030\002 " +
      "\001(\0132\033.google.protobuf.Int32Value\022(\n\003ddd\030" +
      "\003 \001(\0132\033.google.protobuf.Int32Value\022+\n\006nu" +
      "mber\030\004 \001(\0132\033.google.protobuf.Int32Value\022" +
      "2\n\rextensionLine\030\005 \001(\0132\033.google.protobuf" +
      ".Int32Value\"\220\002\n\006Person\022.\n\010tenantId\030\001 \001(\013" +
      "2\034.google.protobuf.StringValue\022.\n\010person" +
      "Id\030\002 \001(\0132\034.google.protobuf.StringValue\022*" +
      "\n\004name\030\003 \001(\0132\034.google.protobuf.StringVal" +
      "ue\022*\n\004type\030\004 \001(\0132\034.google.protobuf.Strin" +
      "gValue\022-\n\007cpfCnpj\030\005 \001(\0132\034.google.protobu" +
      "f.StringValue\022\037\n\006phones\030\006 \003(\0132\017.services" +
      ".Phone\"@\n\017GetPhoneRequest\022-\n\007phoneId\030\001 \001" +
      "(\0132\034.google.protobuf.StringValue2\276\004\n\013Dat" +
      "aService\022;\n\tGetPerson\022\032.services.GetPers" +
      "onRequest\032\020.services.Person\"\000\022:\n\022Validat" +
      "eSavePerson\022\020.services.Person\032\020.services" +
      ".Person\"\000\0222\n\nSavePerson\022\020.services.Perso" +
      "n\032\020.services.Person\"\000\0226\n\016UndoSavePerson\022" +
      "\020.services.Person\032\020.services.Person\"\000\022<\n" +
      "\024ValidateUpdatePerson\022\020.services.Person\032" +
      "\020.services.Person\"\000\0224\n\014UpdatePerson\022\020.se" +
      "rvices.Person\032\020.services.Person\"\000\0228\n\020Und" +
      "oUpdatePerson\022\020.services.Person\032\020.servic" +
      "es.Person\"\000\0228\n\010GetPhone\022\031.services.GetPh" +
      "oneRequest\032\017.services.Phone\"\000\022/\n\tSavePho" +
      "ne\022\017.services.Phone\032\017.services.Phone\"\000\0221" +
      "\n\013UpdatePhone\022\017.services.Phone\032\017.service" +
      "s.Phone\"\000B\033\n\027com.ortiz.grpc.servicesP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_services_GetPersonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_services_GetPersonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_GetPersonRequest_descriptor,
        new java.lang.String[] { "TenantId", "PersonId", });
    internal_static_services_Phone_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_services_Phone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_Phone_descriptor,
        new java.lang.String[] { "Id", "Ddi", "Ddd", "Number", "ExtensionLine", });
    internal_static_services_Person_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_services_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_Person_descriptor,
        new java.lang.String[] { "TenantId", "PersonId", "Name", "Type", "CpfCnpj", "Phones", });
    internal_static_services_GetPhoneRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_services_GetPhoneRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_GetPhoneRequest_descriptor,
        new java.lang.String[] { "PhoneId", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
