// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-service.proto

package com.ortiz.grpc.services;

public interface GetPhoneRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.GetPhoneRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue phoneId = 1;</code>
   * @return Whether the phoneId field is set.
   */
  boolean hasPhoneId();
  /**
   * <code>.google.protobuf.StringValue phoneId = 1;</code>
   * @return The phoneId.
   */
  com.google.protobuf.StringValue getPhoneId();
  /**
   * <code>.google.protobuf.StringValue phoneId = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getPhoneIdOrBuilder();
}
