// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-service.proto

package com.ortiz.grpc.services;

public interface GetPhoneRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.GetPhoneRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phoneId = 1;</code>
   * @return The phoneId.
   */
  java.lang.String getPhoneId();
  /**
   * <code>string phoneId = 1;</code>
   * @return The bytes for phoneId.
   */
  com.google.protobuf.ByteString
      getPhoneIdBytes();
}
