// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-service.proto

package com.ortiz.grpc.services;

/**
 * Protobuf type {@code services.GetPersonRequest}
 */
public final class GetPersonRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:services.GetPersonRequest)
    GetPersonRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPersonRequest.newBuilder() to construct.
  private GetPersonRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPersonRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetPersonRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetPersonRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (tenantId_ != null) {
              subBuilder = tenantId_.toBuilder();
            }
            tenantId_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tenantId_);
              tenantId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (personId_ != null) {
              subBuilder = personId_.toBuilder();
            }
            personId_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(personId_);
              personId_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ortiz.grpc.services.DataServiceOuterClass.internal_static_services_GetPersonRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ortiz.grpc.services.DataServiceOuterClass.internal_static_services_GetPersonRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ortiz.grpc.services.GetPersonRequest.class, com.ortiz.grpc.services.GetPersonRequest.Builder.class);
  }

  public static final int TENANTID_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue tenantId_;
  /**
   * <code>.google.protobuf.StringValue tenantId = 1;</code>
   * @return Whether the tenantId field is set.
   */
  @java.lang.Override
  public boolean hasTenantId() {
    return tenantId_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue tenantId = 1;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getTenantId() {
    return tenantId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : tenantId_;
  }
  /**
   * <code>.google.protobuf.StringValue tenantId = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getTenantIdOrBuilder() {
    return getTenantId();
  }

  public static final int PERSONID_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue personId_;
  /**
   * <code>.google.protobuf.StringValue personId = 2;</code>
   * @return Whether the personId field is set.
   */
  @java.lang.Override
  public boolean hasPersonId() {
    return personId_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue personId = 2;</code>
   * @return The personId.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getPersonId() {
    return personId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : personId_;
  }
  /**
   * <code>.google.protobuf.StringValue personId = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getPersonIdOrBuilder() {
    return getPersonId();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tenantId_ != null) {
      output.writeMessage(1, getTenantId());
    }
    if (personId_ != null) {
      output.writeMessage(2, getPersonId());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tenantId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTenantId());
    }
    if (personId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPersonId());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ortiz.grpc.services.GetPersonRequest)) {
      return super.equals(obj);
    }
    com.ortiz.grpc.services.GetPersonRequest other = (com.ortiz.grpc.services.GetPersonRequest) obj;

    if (hasTenantId() != other.hasTenantId()) return false;
    if (hasTenantId()) {
      if (!getTenantId()
          .equals(other.getTenantId())) return false;
    }
    if (hasPersonId() != other.hasPersonId()) return false;
    if (hasPersonId()) {
      if (!getPersonId()
          .equals(other.getPersonId())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTenantId()) {
      hash = (37 * hash) + TENANTID_FIELD_NUMBER;
      hash = (53 * hash) + getTenantId().hashCode();
    }
    if (hasPersonId()) {
      hash = (37 * hash) + PERSONID_FIELD_NUMBER;
      hash = (53 * hash) + getPersonId().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ortiz.grpc.services.GetPersonRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.GetPersonRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.GetPersonRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.GetPersonRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.GetPersonRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.GetPersonRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.GetPersonRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.GetPersonRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ortiz.grpc.services.GetPersonRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.GetPersonRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ortiz.grpc.services.GetPersonRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.GetPersonRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ortiz.grpc.services.GetPersonRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code services.GetPersonRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:services.GetPersonRequest)
      com.ortiz.grpc.services.GetPersonRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ortiz.grpc.services.DataServiceOuterClass.internal_static_services_GetPersonRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ortiz.grpc.services.DataServiceOuterClass.internal_static_services_GetPersonRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ortiz.grpc.services.GetPersonRequest.class, com.ortiz.grpc.services.GetPersonRequest.Builder.class);
    }

    // Construct using com.ortiz.grpc.services.GetPersonRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (tenantIdBuilder_ == null) {
        tenantId_ = null;
      } else {
        tenantId_ = null;
        tenantIdBuilder_ = null;
      }
      if (personIdBuilder_ == null) {
        personId_ = null;
      } else {
        personId_ = null;
        personIdBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ortiz.grpc.services.DataServiceOuterClass.internal_static_services_GetPersonRequest_descriptor;
    }

    @java.lang.Override
    public com.ortiz.grpc.services.GetPersonRequest getDefaultInstanceForType() {
      return com.ortiz.grpc.services.GetPersonRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ortiz.grpc.services.GetPersonRequest build() {
      com.ortiz.grpc.services.GetPersonRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ortiz.grpc.services.GetPersonRequest buildPartial() {
      com.ortiz.grpc.services.GetPersonRequest result = new com.ortiz.grpc.services.GetPersonRequest(this);
      if (tenantIdBuilder_ == null) {
        result.tenantId_ = tenantId_;
      } else {
        result.tenantId_ = tenantIdBuilder_.build();
      }
      if (personIdBuilder_ == null) {
        result.personId_ = personId_;
      } else {
        result.personId_ = personIdBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ortiz.grpc.services.GetPersonRequest) {
        return mergeFrom((com.ortiz.grpc.services.GetPersonRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ortiz.grpc.services.GetPersonRequest other) {
      if (other == com.ortiz.grpc.services.GetPersonRequest.getDefaultInstance()) return this;
      if (other.hasTenantId()) {
        mergeTenantId(other.getTenantId());
      }
      if (other.hasPersonId()) {
        mergePersonId(other.getPersonId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ortiz.grpc.services.GetPersonRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ortiz.grpc.services.GetPersonRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.StringValue tenantId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> tenantIdBuilder_;
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     * @return Whether the tenantId field is set.
     */
    public boolean hasTenantId() {
      return tenantIdBuilder_ != null || tenantId_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     * @return The tenantId.
     */
    public com.google.protobuf.StringValue getTenantId() {
      if (tenantIdBuilder_ == null) {
        return tenantId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : tenantId_;
      } else {
        return tenantIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public Builder setTenantId(com.google.protobuf.StringValue value) {
      if (tenantIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tenantId_ = value;
        onChanged();
      } else {
        tenantIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public Builder setTenantId(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (tenantIdBuilder_ == null) {
        tenantId_ = builderForValue.build();
        onChanged();
      } else {
        tenantIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public Builder mergeTenantId(com.google.protobuf.StringValue value) {
      if (tenantIdBuilder_ == null) {
        if (tenantId_ != null) {
          tenantId_ =
            com.google.protobuf.StringValue.newBuilder(tenantId_).mergeFrom(value).buildPartial();
        } else {
          tenantId_ = value;
        }
        onChanged();
      } else {
        tenantIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public Builder clearTenantId() {
      if (tenantIdBuilder_ == null) {
        tenantId_ = null;
        onChanged();
      } else {
        tenantId_ = null;
        tenantIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getTenantIdBuilder() {
      
      onChanged();
      return getTenantIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getTenantIdOrBuilder() {
      if (tenantIdBuilder_ != null) {
        return tenantIdBuilder_.getMessageOrBuilder();
      } else {
        return tenantId_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : tenantId_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getTenantIdFieldBuilder() {
      if (tenantIdBuilder_ == null) {
        tenantIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getTenantId(),
                getParentForChildren(),
                isClean());
        tenantId_ = null;
      }
      return tenantIdBuilder_;
    }

    private com.google.protobuf.StringValue personId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> personIdBuilder_;
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     * @return Whether the personId field is set.
     */
    public boolean hasPersonId() {
      return personIdBuilder_ != null || personId_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     * @return The personId.
     */
    public com.google.protobuf.StringValue getPersonId() {
      if (personIdBuilder_ == null) {
        return personId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : personId_;
      } else {
        return personIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public Builder setPersonId(com.google.protobuf.StringValue value) {
      if (personIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        personId_ = value;
        onChanged();
      } else {
        personIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public Builder setPersonId(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (personIdBuilder_ == null) {
        personId_ = builderForValue.build();
        onChanged();
      } else {
        personIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public Builder mergePersonId(com.google.protobuf.StringValue value) {
      if (personIdBuilder_ == null) {
        if (personId_ != null) {
          personId_ =
            com.google.protobuf.StringValue.newBuilder(personId_).mergeFrom(value).buildPartial();
        } else {
          personId_ = value;
        }
        onChanged();
      } else {
        personIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public Builder clearPersonId() {
      if (personIdBuilder_ == null) {
        personId_ = null;
        onChanged();
      } else {
        personId_ = null;
        personIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getPersonIdBuilder() {
      
      onChanged();
      return getPersonIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getPersonIdOrBuilder() {
      if (personIdBuilder_ != null) {
        return personIdBuilder_.getMessageOrBuilder();
      } else {
        return personId_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : personId_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getPersonIdFieldBuilder() {
      if (personIdBuilder_ == null) {
        personIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getPersonId(),
                getParentForChildren(),
                isClean());
        personId_ = null;
      }
      return personIdBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:services.GetPersonRequest)
  }

  // @@protoc_insertion_point(class_scope:services.GetPersonRequest)
  private static final com.ortiz.grpc.services.GetPersonRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ortiz.grpc.services.GetPersonRequest();
  }

  public static com.ortiz.grpc.services.GetPersonRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPersonRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetPersonRequest>() {
    @java.lang.Override
    public GetPersonRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetPersonRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetPersonRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPersonRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ortiz.grpc.services.GetPersonRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

