// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-service.proto

package com.ortiz.grpc.services;

/**
 * Protobuf type {@code services.Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:services.Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    phones_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Person(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (tenantId_ != null) {
              subBuilder = tenantId_.toBuilder();
            }
            tenantId_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tenantId_);
              tenantId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (personId_ != null) {
              subBuilder = personId_.toBuilder();
            }
            personId_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(personId_);
              personId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (name_ != null) {
              subBuilder = name_.toBuilder();
            }
            name_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(name_);
              name_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (type_ != null) {
              subBuilder = type_.toBuilder();
            }
            type_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(type_);
              type_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (cpfCnpj_ != null) {
              subBuilder = cpfCnpj_.toBuilder();
            }
            cpfCnpj_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cpfCnpj_);
              cpfCnpj_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              phones_ = new java.util.ArrayList<com.ortiz.grpc.services.Phone>();
              mutable_bitField0_ |= 0x00000001;
            }
            phones_.add(
                input.readMessage(com.ortiz.grpc.services.Phone.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        phones_ = java.util.Collections.unmodifiableList(phones_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ortiz.grpc.services.DataServiceOuterClass.internal_static_services_Person_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ortiz.grpc.services.DataServiceOuterClass.internal_static_services_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ortiz.grpc.services.Person.class, com.ortiz.grpc.services.Person.Builder.class);
  }

  public static final int TENANTID_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue tenantId_;
  /**
   * <code>.google.protobuf.StringValue tenantId = 1;</code>
   * @return Whether the tenantId field is set.
   */
  @java.lang.Override
  public boolean hasTenantId() {
    return tenantId_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue tenantId = 1;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getTenantId() {
    return tenantId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : tenantId_;
  }
  /**
   * <code>.google.protobuf.StringValue tenantId = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getTenantIdOrBuilder() {
    return getTenantId();
  }

  public static final int PERSONID_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue personId_;
  /**
   * <code>.google.protobuf.StringValue personId = 2;</code>
   * @return Whether the personId field is set.
   */
  @java.lang.Override
  public boolean hasPersonId() {
    return personId_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue personId = 2;</code>
   * @return The personId.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getPersonId() {
    return personId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : personId_;
  }
  /**
   * <code>.google.protobuf.StringValue personId = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getPersonIdOrBuilder() {
    return getPersonId();
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private com.google.protobuf.StringValue name_;
  /**
   * <code>.google.protobuf.StringValue name = 3;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return name_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getName() {
    return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
  }
  /**
   * <code>.google.protobuf.StringValue name = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
    return getName();
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private com.google.protobuf.StringValue type_;
  /**
   * <code>.google.protobuf.StringValue type = 4;</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override
  public boolean hasType() {
    return type_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue type = 4;</code>
   * @return The type.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getType() {
    return type_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : type_;
  }
  /**
   * <code>.google.protobuf.StringValue type = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getTypeOrBuilder() {
    return getType();
  }

  public static final int CPFCNPJ_FIELD_NUMBER = 5;
  private com.google.protobuf.StringValue cpfCnpj_;
  /**
   * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
   * @return Whether the cpfCnpj field is set.
   */
  @java.lang.Override
  public boolean hasCpfCnpj() {
    return cpfCnpj_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
   * @return The cpfCnpj.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getCpfCnpj() {
    return cpfCnpj_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : cpfCnpj_;
  }
  /**
   * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getCpfCnpjOrBuilder() {
    return getCpfCnpj();
  }

  public static final int PHONES_FIELD_NUMBER = 6;
  private java.util.List<com.ortiz.grpc.services.Phone> phones_;
  /**
   * <code>repeated .services.Phone phones = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.ortiz.grpc.services.Phone> getPhonesList() {
    return phones_;
  }
  /**
   * <code>repeated .services.Phone phones = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ortiz.grpc.services.PhoneOrBuilder> 
      getPhonesOrBuilderList() {
    return phones_;
  }
  /**
   * <code>repeated .services.Phone phones = 6;</code>
   */
  @java.lang.Override
  public int getPhonesCount() {
    return phones_.size();
  }
  /**
   * <code>repeated .services.Phone phones = 6;</code>
   */
  @java.lang.Override
  public com.ortiz.grpc.services.Phone getPhones(int index) {
    return phones_.get(index);
  }
  /**
   * <code>repeated .services.Phone phones = 6;</code>
   */
  @java.lang.Override
  public com.ortiz.grpc.services.PhoneOrBuilder getPhonesOrBuilder(
      int index) {
    return phones_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tenantId_ != null) {
      output.writeMessage(1, getTenantId());
    }
    if (personId_ != null) {
      output.writeMessage(2, getPersonId());
    }
    if (name_ != null) {
      output.writeMessage(3, getName());
    }
    if (type_ != null) {
      output.writeMessage(4, getType());
    }
    if (cpfCnpj_ != null) {
      output.writeMessage(5, getCpfCnpj());
    }
    for (int i = 0; i < phones_.size(); i++) {
      output.writeMessage(6, phones_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tenantId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTenantId());
    }
    if (personId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPersonId());
    }
    if (name_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getName());
    }
    if (type_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getType());
    }
    if (cpfCnpj_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getCpfCnpj());
    }
    for (int i = 0; i < phones_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, phones_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ortiz.grpc.services.Person)) {
      return super.equals(obj);
    }
    com.ortiz.grpc.services.Person other = (com.ortiz.grpc.services.Person) obj;

    if (hasTenantId() != other.hasTenantId()) return false;
    if (hasTenantId()) {
      if (!getTenantId()
          .equals(other.getTenantId())) return false;
    }
    if (hasPersonId() != other.hasPersonId()) return false;
    if (hasPersonId()) {
      if (!getPersonId()
          .equals(other.getPersonId())) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (!getType()
          .equals(other.getType())) return false;
    }
    if (hasCpfCnpj() != other.hasCpfCnpj()) return false;
    if (hasCpfCnpj()) {
      if (!getCpfCnpj()
          .equals(other.getCpfCnpj())) return false;
    }
    if (!getPhonesList()
        .equals(other.getPhonesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTenantId()) {
      hash = (37 * hash) + TENANTID_FIELD_NUMBER;
      hash = (53 * hash) + getTenantId().hashCode();
    }
    if (hasPersonId()) {
      hash = (37 * hash) + PERSONID_FIELD_NUMBER;
      hash = (53 * hash) + getPersonId().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
    }
    if (hasCpfCnpj()) {
      hash = (37 * hash) + CPFCNPJ_FIELD_NUMBER;
      hash = (53 * hash) + getCpfCnpj().hashCode();
    }
    if (getPhonesCount() > 0) {
      hash = (37 * hash) + PHONES_FIELD_NUMBER;
      hash = (53 * hash) + getPhonesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ortiz.grpc.services.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ortiz.grpc.services.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ortiz.grpc.services.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ortiz.grpc.services.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code services.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:services.Person)
      com.ortiz.grpc.services.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ortiz.grpc.services.DataServiceOuterClass.internal_static_services_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ortiz.grpc.services.DataServiceOuterClass.internal_static_services_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ortiz.grpc.services.Person.class, com.ortiz.grpc.services.Person.Builder.class);
    }

    // Construct using com.ortiz.grpc.services.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPhonesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (tenantIdBuilder_ == null) {
        tenantId_ = null;
      } else {
        tenantId_ = null;
        tenantIdBuilder_ = null;
      }
      if (personIdBuilder_ == null) {
        personId_ = null;
      } else {
        personId_ = null;
        personIdBuilder_ = null;
      }
      if (nameBuilder_ == null) {
        name_ = null;
      } else {
        name_ = null;
        nameBuilder_ = null;
      }
      if (typeBuilder_ == null) {
        type_ = null;
      } else {
        type_ = null;
        typeBuilder_ = null;
      }
      if (cpfCnpjBuilder_ == null) {
        cpfCnpj_ = null;
      } else {
        cpfCnpj_ = null;
        cpfCnpjBuilder_ = null;
      }
      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        phonesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ortiz.grpc.services.DataServiceOuterClass.internal_static_services_Person_descriptor;
    }

    @java.lang.Override
    public com.ortiz.grpc.services.Person getDefaultInstanceForType() {
      return com.ortiz.grpc.services.Person.getDefaultInstance();
    }

    @java.lang.Override
    public com.ortiz.grpc.services.Person build() {
      com.ortiz.grpc.services.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ortiz.grpc.services.Person buildPartial() {
      com.ortiz.grpc.services.Person result = new com.ortiz.grpc.services.Person(this);
      int from_bitField0_ = bitField0_;
      if (tenantIdBuilder_ == null) {
        result.tenantId_ = tenantId_;
      } else {
        result.tenantId_ = tenantIdBuilder_.build();
      }
      if (personIdBuilder_ == null) {
        result.personId_ = personId_;
      } else {
        result.personId_ = personIdBuilder_.build();
      }
      if (nameBuilder_ == null) {
        result.name_ = name_;
      } else {
        result.name_ = nameBuilder_.build();
      }
      if (typeBuilder_ == null) {
        result.type_ = type_;
      } else {
        result.type_ = typeBuilder_.build();
      }
      if (cpfCnpjBuilder_ == null) {
        result.cpfCnpj_ = cpfCnpj_;
      } else {
        result.cpfCnpj_ = cpfCnpjBuilder_.build();
      }
      if (phonesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          phones_ = java.util.Collections.unmodifiableList(phones_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.phones_ = phones_;
      } else {
        result.phones_ = phonesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ortiz.grpc.services.Person) {
        return mergeFrom((com.ortiz.grpc.services.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ortiz.grpc.services.Person other) {
      if (other == com.ortiz.grpc.services.Person.getDefaultInstance()) return this;
      if (other.hasTenantId()) {
        mergeTenantId(other.getTenantId());
      }
      if (other.hasPersonId()) {
        mergePersonId(other.getPersonId());
      }
      if (other.hasName()) {
        mergeName(other.getName());
      }
      if (other.hasType()) {
        mergeType(other.getType());
      }
      if (other.hasCpfCnpj()) {
        mergeCpfCnpj(other.getCpfCnpj());
      }
      if (phonesBuilder_ == null) {
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
      } else {
        if (!other.phones_.isEmpty()) {
          if (phonesBuilder_.isEmpty()) {
            phonesBuilder_.dispose();
            phonesBuilder_ = null;
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000001);
            phonesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhonesFieldBuilder() : null;
          } else {
            phonesBuilder_.addAllMessages(other.phones_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ortiz.grpc.services.Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ortiz.grpc.services.Person) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.StringValue tenantId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> tenantIdBuilder_;
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     * @return Whether the tenantId field is set.
     */
    public boolean hasTenantId() {
      return tenantIdBuilder_ != null || tenantId_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     * @return The tenantId.
     */
    public com.google.protobuf.StringValue getTenantId() {
      if (tenantIdBuilder_ == null) {
        return tenantId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : tenantId_;
      } else {
        return tenantIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public Builder setTenantId(com.google.protobuf.StringValue value) {
      if (tenantIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tenantId_ = value;
        onChanged();
      } else {
        tenantIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public Builder setTenantId(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (tenantIdBuilder_ == null) {
        tenantId_ = builderForValue.build();
        onChanged();
      } else {
        tenantIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public Builder mergeTenantId(com.google.protobuf.StringValue value) {
      if (tenantIdBuilder_ == null) {
        if (tenantId_ != null) {
          tenantId_ =
            com.google.protobuf.StringValue.newBuilder(tenantId_).mergeFrom(value).buildPartial();
        } else {
          tenantId_ = value;
        }
        onChanged();
      } else {
        tenantIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public Builder clearTenantId() {
      if (tenantIdBuilder_ == null) {
        tenantId_ = null;
        onChanged();
      } else {
        tenantId_ = null;
        tenantIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getTenantIdBuilder() {
      
      onChanged();
      return getTenantIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getTenantIdOrBuilder() {
      if (tenantIdBuilder_ != null) {
        return tenantIdBuilder_.getMessageOrBuilder();
      } else {
        return tenantId_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : tenantId_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getTenantIdFieldBuilder() {
      if (tenantIdBuilder_ == null) {
        tenantIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getTenantId(),
                getParentForChildren(),
                isClean());
        tenantId_ = null;
      }
      return tenantIdBuilder_;
    }

    private com.google.protobuf.StringValue personId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> personIdBuilder_;
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     * @return Whether the personId field is set.
     */
    public boolean hasPersonId() {
      return personIdBuilder_ != null || personId_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     * @return The personId.
     */
    public com.google.protobuf.StringValue getPersonId() {
      if (personIdBuilder_ == null) {
        return personId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : personId_;
      } else {
        return personIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public Builder setPersonId(com.google.protobuf.StringValue value) {
      if (personIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        personId_ = value;
        onChanged();
      } else {
        personIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public Builder setPersonId(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (personIdBuilder_ == null) {
        personId_ = builderForValue.build();
        onChanged();
      } else {
        personIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public Builder mergePersonId(com.google.protobuf.StringValue value) {
      if (personIdBuilder_ == null) {
        if (personId_ != null) {
          personId_ =
            com.google.protobuf.StringValue.newBuilder(personId_).mergeFrom(value).buildPartial();
        } else {
          personId_ = value;
        }
        onChanged();
      } else {
        personIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public Builder clearPersonId() {
      if (personIdBuilder_ == null) {
        personId_ = null;
        onChanged();
      } else {
        personId_ = null;
        personIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getPersonIdBuilder() {
      
      onChanged();
      return getPersonIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getPersonIdOrBuilder() {
      if (personIdBuilder_ != null) {
        return personIdBuilder_.getMessageOrBuilder();
      } else {
        return personId_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : personId_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue personId = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getPersonIdFieldBuilder() {
      if (personIdBuilder_ == null) {
        personIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getPersonId(),
                getParentForChildren(),
                isClean());
        personId_ = null;
      }
      return personIdBuilder_;
    }

    private com.google.protobuf.StringValue name_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> nameBuilder_;
    /**
     * <code>.google.protobuf.StringValue name = 3;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return nameBuilder_ != null || name_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue name = 3;</code>
     * @return The name.
     */
    public com.google.protobuf.StringValue getName() {
      if (nameBuilder_ == null) {
        return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
      } else {
        return nameBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue name = 3;</code>
     */
    public Builder setName(com.google.protobuf.StringValue value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        name_ = value;
        onChanged();
      } else {
        nameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 3;</code>
     */
    public Builder setName(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (nameBuilder_ == null) {
        name_ = builderForValue.build();
        onChanged();
      } else {
        nameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 3;</code>
     */
    public Builder mergeName(com.google.protobuf.StringValue value) {
      if (nameBuilder_ == null) {
        if (name_ != null) {
          name_ =
            com.google.protobuf.StringValue.newBuilder(name_).mergeFrom(value).buildPartial();
        } else {
          name_ = value;
        }
        onChanged();
      } else {
        nameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 3;</code>
     */
    public Builder clearName() {
      if (nameBuilder_ == null) {
        name_ = null;
        onChanged();
      } else {
        name_ = null;
        nameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 3;</code>
     */
    public com.google.protobuf.StringValue.Builder getNameBuilder() {
      
      onChanged();
      return getNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue name = 3;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
      if (nameBuilder_ != null) {
        return nameBuilder_.getMessageOrBuilder();
      } else {
        return name_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : name_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue name = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getNameFieldBuilder() {
      if (nameBuilder_ == null) {
        nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getName(),
                getParentForChildren(),
                isClean());
        name_ = null;
      }
      return nameBuilder_;
    }

    private com.google.protobuf.StringValue type_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> typeBuilder_;
    /**
     * <code>.google.protobuf.StringValue type = 4;</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return typeBuilder_ != null || type_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue type = 4;</code>
     * @return The type.
     */
    public com.google.protobuf.StringValue getType() {
      if (typeBuilder_ == null) {
        return type_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : type_;
      } else {
        return typeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue type = 4;</code>
     */
    public Builder setType(com.google.protobuf.StringValue value) {
      if (typeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
        onChanged();
      } else {
        typeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue type = 4;</code>
     */
    public Builder setType(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (typeBuilder_ == null) {
        type_ = builderForValue.build();
        onChanged();
      } else {
        typeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue type = 4;</code>
     */
    public Builder mergeType(com.google.protobuf.StringValue value) {
      if (typeBuilder_ == null) {
        if (type_ != null) {
          type_ =
            com.google.protobuf.StringValue.newBuilder(type_).mergeFrom(value).buildPartial();
        } else {
          type_ = value;
        }
        onChanged();
      } else {
        typeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue type = 4;</code>
     */
    public Builder clearType() {
      if (typeBuilder_ == null) {
        type_ = null;
        onChanged();
      } else {
        type_ = null;
        typeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue type = 4;</code>
     */
    public com.google.protobuf.StringValue.Builder getTypeBuilder() {
      
      onChanged();
      return getTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue type = 4;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getTypeOrBuilder() {
      if (typeBuilder_ != null) {
        return typeBuilder_.getMessageOrBuilder();
      } else {
        return type_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : type_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue type = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getTypeFieldBuilder() {
      if (typeBuilder_ == null) {
        typeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getType(),
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      return typeBuilder_;
    }

    private com.google.protobuf.StringValue cpfCnpj_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> cpfCnpjBuilder_;
    /**
     * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
     * @return Whether the cpfCnpj field is set.
     */
    public boolean hasCpfCnpj() {
      return cpfCnpjBuilder_ != null || cpfCnpj_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
     * @return The cpfCnpj.
     */
    public com.google.protobuf.StringValue getCpfCnpj() {
      if (cpfCnpjBuilder_ == null) {
        return cpfCnpj_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : cpfCnpj_;
      } else {
        return cpfCnpjBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
     */
    public Builder setCpfCnpj(com.google.protobuf.StringValue value) {
      if (cpfCnpjBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cpfCnpj_ = value;
        onChanged();
      } else {
        cpfCnpjBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
     */
    public Builder setCpfCnpj(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (cpfCnpjBuilder_ == null) {
        cpfCnpj_ = builderForValue.build();
        onChanged();
      } else {
        cpfCnpjBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
     */
    public Builder mergeCpfCnpj(com.google.protobuf.StringValue value) {
      if (cpfCnpjBuilder_ == null) {
        if (cpfCnpj_ != null) {
          cpfCnpj_ =
            com.google.protobuf.StringValue.newBuilder(cpfCnpj_).mergeFrom(value).buildPartial();
        } else {
          cpfCnpj_ = value;
        }
        onChanged();
      } else {
        cpfCnpjBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
     */
    public Builder clearCpfCnpj() {
      if (cpfCnpjBuilder_ == null) {
        cpfCnpj_ = null;
        onChanged();
      } else {
        cpfCnpj_ = null;
        cpfCnpjBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
     */
    public com.google.protobuf.StringValue.Builder getCpfCnpjBuilder() {
      
      onChanged();
      return getCpfCnpjFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getCpfCnpjOrBuilder() {
      if (cpfCnpjBuilder_ != null) {
        return cpfCnpjBuilder_.getMessageOrBuilder();
      } else {
        return cpfCnpj_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : cpfCnpj_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue cpfCnpj = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getCpfCnpjFieldBuilder() {
      if (cpfCnpjBuilder_ == null) {
        cpfCnpjBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getCpfCnpj(),
                getParentForChildren(),
                isClean());
        cpfCnpj_ = null;
      }
      return cpfCnpjBuilder_;
    }

    private java.util.List<com.ortiz.grpc.services.Phone> phones_ =
      java.util.Collections.emptyList();
    private void ensurePhonesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        phones_ = new java.util.ArrayList<com.ortiz.grpc.services.Phone>(phones_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ortiz.grpc.services.Phone, com.ortiz.grpc.services.Phone.Builder, com.ortiz.grpc.services.PhoneOrBuilder> phonesBuilder_;

    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public java.util.List<com.ortiz.grpc.services.Phone> getPhonesList() {
      if (phonesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phones_);
      } else {
        return phonesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public int getPhonesCount() {
      if (phonesBuilder_ == null) {
        return phones_.size();
      } else {
        return phonesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public com.ortiz.grpc.services.Phone getPhones(int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);
      } else {
        return phonesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public Builder setPhones(
        int index, com.ortiz.grpc.services.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public Builder setPhones(
        int index, com.ortiz.grpc.services.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.set(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public Builder addPhones(com.ortiz.grpc.services.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public Builder addPhones(
        int index, com.ortiz.grpc.services.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(index, value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public Builder addPhones(
        com.ortiz.grpc.services.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public Builder addPhones(
        int index, com.ortiz.grpc.services.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public Builder addAllPhones(
        java.lang.Iterable<? extends com.ortiz.grpc.services.Phone> values) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
      } else {
        phonesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public Builder clearPhones() {
      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        phonesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public Builder removePhones(int index) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.remove(index);
        onChanged();
      } else {
        phonesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public com.ortiz.grpc.services.Phone.Builder getPhonesBuilder(
        int index) {
      return getPhonesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public com.ortiz.grpc.services.PhoneOrBuilder getPhonesOrBuilder(
        int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);  } else {
        return phonesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public java.util.List<? extends com.ortiz.grpc.services.PhoneOrBuilder> 
         getPhonesOrBuilderList() {
      if (phonesBuilder_ != null) {
        return phonesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phones_);
      }
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public com.ortiz.grpc.services.Phone.Builder addPhonesBuilder() {
      return getPhonesFieldBuilder().addBuilder(
          com.ortiz.grpc.services.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public com.ortiz.grpc.services.Phone.Builder addPhonesBuilder(
        int index) {
      return getPhonesFieldBuilder().addBuilder(
          index, com.ortiz.grpc.services.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .services.Phone phones = 6;</code>
     */
    public java.util.List<com.ortiz.grpc.services.Phone.Builder> 
         getPhonesBuilderList() {
      return getPhonesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ortiz.grpc.services.Phone, com.ortiz.grpc.services.Phone.Builder, com.ortiz.grpc.services.PhoneOrBuilder> 
        getPhonesFieldBuilder() {
      if (phonesBuilder_ == null) {
        phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ortiz.grpc.services.Phone, com.ortiz.grpc.services.Phone.Builder, com.ortiz.grpc.services.PhoneOrBuilder>(
                phones_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        phones_ = null;
      }
      return phonesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:services.Person)
  }

  // @@protoc_insertion_point(class_scope:services.Person)
  private static final com.ortiz.grpc.services.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ortiz.grpc.services.Person();
  }

  public static com.ortiz.grpc.services.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Person(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ortiz.grpc.services.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

