// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-service.proto

package com.ortiz.grpc.services;

public interface GetPersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.GetPersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tenantId = 1;</code>
   * @return The tenantId.
   */
  String getTenantId();
  /**
   * <code>string tenantId = 1;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 4;</code>
   * @return The type.
   */
  String getType();
  /**
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string cpfCnpj = 5;</code>
   * @return The cpfCnpj.
   */
  String getCpfCnpj();
  /**
   * <code>string cpfCnpj = 5;</code>
   * @return The bytes for cpfCnpj.
   */
  com.google.protobuf.ByteString
      getCpfCnpjBytes();
}
