// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validation-fields-service.proto

package com.ortiz.grpc.services.vfs;

/**
 * Protobuf type {@code services.ValidationFields}
 */
public final class ValidationFields extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:services.ValidationFields)
    ValidationFieldsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ValidationFields.newBuilder() to construct.
  private ValidationFields(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValidationFields() {
    verifiedFields_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ValidationFields();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ValidationFields(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              verifiedFields_ = new java.util.ArrayList<com.ortiz.grpc.services.vfs.ValidationField>();
              mutable_bitField0_ |= 0x00000001;
            }
            verifiedFields_.add(
                input.readMessage(com.ortiz.grpc.services.vfs.ValidationField.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        verifiedFields_ = java.util.Collections.unmodifiableList(verifiedFields_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ortiz.grpc.services.vfs.ValidationFieldsServiceOuterClass.internal_static_services_ValidationFields_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ortiz.grpc.services.vfs.ValidationFieldsServiceOuterClass.internal_static_services_ValidationFields_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ortiz.grpc.services.vfs.ValidationFields.class, com.ortiz.grpc.services.vfs.ValidationFields.Builder.class);
  }

  public static final int VERIFIEDFIELDS_FIELD_NUMBER = 1;
  private java.util.List<com.ortiz.grpc.services.vfs.ValidationField> verifiedFields_;
  /**
   * <code>repeated .services.ValidationField verifiedFields = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.ortiz.grpc.services.vfs.ValidationField> getVerifiedFieldsList() {
    return verifiedFields_;
  }
  /**
   * <code>repeated .services.ValidationField verifiedFields = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ortiz.grpc.services.vfs.ValidationFieldOrBuilder> 
      getVerifiedFieldsOrBuilderList() {
    return verifiedFields_;
  }
  /**
   * <code>repeated .services.ValidationField verifiedFields = 1;</code>
   */
  @java.lang.Override
  public int getVerifiedFieldsCount() {
    return verifiedFields_.size();
  }
  /**
   * <code>repeated .services.ValidationField verifiedFields = 1;</code>
   */
  @java.lang.Override
  public com.ortiz.grpc.services.vfs.ValidationField getVerifiedFields(int index) {
    return verifiedFields_.get(index);
  }
  /**
   * <code>repeated .services.ValidationField verifiedFields = 1;</code>
   */
  @java.lang.Override
  public com.ortiz.grpc.services.vfs.ValidationFieldOrBuilder getVerifiedFieldsOrBuilder(
      int index) {
    return verifiedFields_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < verifiedFields_.size(); i++) {
      output.writeMessage(1, verifiedFields_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < verifiedFields_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, verifiedFields_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ortiz.grpc.services.vfs.ValidationFields)) {
      return super.equals(obj);
    }
    com.ortiz.grpc.services.vfs.ValidationFields other = (com.ortiz.grpc.services.vfs.ValidationFields) obj;

    if (!getVerifiedFieldsList()
        .equals(other.getVerifiedFieldsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVerifiedFieldsCount() > 0) {
      hash = (37 * hash) + VERIFIEDFIELDS_FIELD_NUMBER;
      hash = (53 * hash) + getVerifiedFieldsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ortiz.grpc.services.vfs.ValidationFields parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.vfs.ValidationFields parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.vfs.ValidationFields parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.vfs.ValidationFields parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.vfs.ValidationFields parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.vfs.ValidationFields parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.vfs.ValidationFields parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.vfs.ValidationFields parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ortiz.grpc.services.vfs.ValidationFields parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.vfs.ValidationFields parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ortiz.grpc.services.vfs.ValidationFields parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.vfs.ValidationFields parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ortiz.grpc.services.vfs.ValidationFields prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code services.ValidationFields}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:services.ValidationFields)
      com.ortiz.grpc.services.vfs.ValidationFieldsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ortiz.grpc.services.vfs.ValidationFieldsServiceOuterClass.internal_static_services_ValidationFields_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ortiz.grpc.services.vfs.ValidationFieldsServiceOuterClass.internal_static_services_ValidationFields_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ortiz.grpc.services.vfs.ValidationFields.class, com.ortiz.grpc.services.vfs.ValidationFields.Builder.class);
    }

    // Construct using com.ortiz.grpc.services.vfs.ValidationFields.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVerifiedFieldsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (verifiedFieldsBuilder_ == null) {
        verifiedFields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        verifiedFieldsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ortiz.grpc.services.vfs.ValidationFieldsServiceOuterClass.internal_static_services_ValidationFields_descriptor;
    }

    @java.lang.Override
    public com.ortiz.grpc.services.vfs.ValidationFields getDefaultInstanceForType() {
      return com.ortiz.grpc.services.vfs.ValidationFields.getDefaultInstance();
    }

    @java.lang.Override
    public com.ortiz.grpc.services.vfs.ValidationFields build() {
      com.ortiz.grpc.services.vfs.ValidationFields result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ortiz.grpc.services.vfs.ValidationFields buildPartial() {
      com.ortiz.grpc.services.vfs.ValidationFields result = new com.ortiz.grpc.services.vfs.ValidationFields(this);
      int from_bitField0_ = bitField0_;
      if (verifiedFieldsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          verifiedFields_ = java.util.Collections.unmodifiableList(verifiedFields_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.verifiedFields_ = verifiedFields_;
      } else {
        result.verifiedFields_ = verifiedFieldsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ortiz.grpc.services.vfs.ValidationFields) {
        return mergeFrom((com.ortiz.grpc.services.vfs.ValidationFields)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ortiz.grpc.services.vfs.ValidationFields other) {
      if (other == com.ortiz.grpc.services.vfs.ValidationFields.getDefaultInstance()) return this;
      if (verifiedFieldsBuilder_ == null) {
        if (!other.verifiedFields_.isEmpty()) {
          if (verifiedFields_.isEmpty()) {
            verifiedFields_ = other.verifiedFields_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVerifiedFieldsIsMutable();
            verifiedFields_.addAll(other.verifiedFields_);
          }
          onChanged();
        }
      } else {
        if (!other.verifiedFields_.isEmpty()) {
          if (verifiedFieldsBuilder_.isEmpty()) {
            verifiedFieldsBuilder_.dispose();
            verifiedFieldsBuilder_ = null;
            verifiedFields_ = other.verifiedFields_;
            bitField0_ = (bitField0_ & ~0x00000001);
            verifiedFieldsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVerifiedFieldsFieldBuilder() : null;
          } else {
            verifiedFieldsBuilder_.addAllMessages(other.verifiedFields_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ortiz.grpc.services.vfs.ValidationFields parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ortiz.grpc.services.vfs.ValidationFields) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ortiz.grpc.services.vfs.ValidationField> verifiedFields_ =
      java.util.Collections.emptyList();
    private void ensureVerifiedFieldsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        verifiedFields_ = new java.util.ArrayList<com.ortiz.grpc.services.vfs.ValidationField>(verifiedFields_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ortiz.grpc.services.vfs.ValidationField, com.ortiz.grpc.services.vfs.ValidationField.Builder, com.ortiz.grpc.services.vfs.ValidationFieldOrBuilder> verifiedFieldsBuilder_;

    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public java.util.List<com.ortiz.grpc.services.vfs.ValidationField> getVerifiedFieldsList() {
      if (verifiedFieldsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(verifiedFields_);
      } else {
        return verifiedFieldsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public int getVerifiedFieldsCount() {
      if (verifiedFieldsBuilder_ == null) {
        return verifiedFields_.size();
      } else {
        return verifiedFieldsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public com.ortiz.grpc.services.vfs.ValidationField getVerifiedFields(int index) {
      if (verifiedFieldsBuilder_ == null) {
        return verifiedFields_.get(index);
      } else {
        return verifiedFieldsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public Builder setVerifiedFields(
        int index, com.ortiz.grpc.services.vfs.ValidationField value) {
      if (verifiedFieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVerifiedFieldsIsMutable();
        verifiedFields_.set(index, value);
        onChanged();
      } else {
        verifiedFieldsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public Builder setVerifiedFields(
        int index, com.ortiz.grpc.services.vfs.ValidationField.Builder builderForValue) {
      if (verifiedFieldsBuilder_ == null) {
        ensureVerifiedFieldsIsMutable();
        verifiedFields_.set(index, builderForValue.build());
        onChanged();
      } else {
        verifiedFieldsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public Builder addVerifiedFields(com.ortiz.grpc.services.vfs.ValidationField value) {
      if (verifiedFieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVerifiedFieldsIsMutable();
        verifiedFields_.add(value);
        onChanged();
      } else {
        verifiedFieldsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public Builder addVerifiedFields(
        int index, com.ortiz.grpc.services.vfs.ValidationField value) {
      if (verifiedFieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVerifiedFieldsIsMutable();
        verifiedFields_.add(index, value);
        onChanged();
      } else {
        verifiedFieldsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public Builder addVerifiedFields(
        com.ortiz.grpc.services.vfs.ValidationField.Builder builderForValue) {
      if (verifiedFieldsBuilder_ == null) {
        ensureVerifiedFieldsIsMutable();
        verifiedFields_.add(builderForValue.build());
        onChanged();
      } else {
        verifiedFieldsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public Builder addVerifiedFields(
        int index, com.ortiz.grpc.services.vfs.ValidationField.Builder builderForValue) {
      if (verifiedFieldsBuilder_ == null) {
        ensureVerifiedFieldsIsMutable();
        verifiedFields_.add(index, builderForValue.build());
        onChanged();
      } else {
        verifiedFieldsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public Builder addAllVerifiedFields(
        java.lang.Iterable<? extends com.ortiz.grpc.services.vfs.ValidationField> values) {
      if (verifiedFieldsBuilder_ == null) {
        ensureVerifiedFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, verifiedFields_);
        onChanged();
      } else {
        verifiedFieldsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public Builder clearVerifiedFields() {
      if (verifiedFieldsBuilder_ == null) {
        verifiedFields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        verifiedFieldsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public Builder removeVerifiedFields(int index) {
      if (verifiedFieldsBuilder_ == null) {
        ensureVerifiedFieldsIsMutable();
        verifiedFields_.remove(index);
        onChanged();
      } else {
        verifiedFieldsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public com.ortiz.grpc.services.vfs.ValidationField.Builder getVerifiedFieldsBuilder(
        int index) {
      return getVerifiedFieldsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public com.ortiz.grpc.services.vfs.ValidationFieldOrBuilder getVerifiedFieldsOrBuilder(
        int index) {
      if (verifiedFieldsBuilder_ == null) {
        return verifiedFields_.get(index);  } else {
        return verifiedFieldsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public java.util.List<? extends com.ortiz.grpc.services.vfs.ValidationFieldOrBuilder> 
         getVerifiedFieldsOrBuilderList() {
      if (verifiedFieldsBuilder_ != null) {
        return verifiedFieldsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(verifiedFields_);
      }
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public com.ortiz.grpc.services.vfs.ValidationField.Builder addVerifiedFieldsBuilder() {
      return getVerifiedFieldsFieldBuilder().addBuilder(
          com.ortiz.grpc.services.vfs.ValidationField.getDefaultInstance());
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public com.ortiz.grpc.services.vfs.ValidationField.Builder addVerifiedFieldsBuilder(
        int index) {
      return getVerifiedFieldsFieldBuilder().addBuilder(
          index, com.ortiz.grpc.services.vfs.ValidationField.getDefaultInstance());
    }
    /**
     * <code>repeated .services.ValidationField verifiedFields = 1;</code>
     */
    public java.util.List<com.ortiz.grpc.services.vfs.ValidationField.Builder> 
         getVerifiedFieldsBuilderList() {
      return getVerifiedFieldsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ortiz.grpc.services.vfs.ValidationField, com.ortiz.grpc.services.vfs.ValidationField.Builder, com.ortiz.grpc.services.vfs.ValidationFieldOrBuilder> 
        getVerifiedFieldsFieldBuilder() {
      if (verifiedFieldsBuilder_ == null) {
        verifiedFieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ortiz.grpc.services.vfs.ValidationField, com.ortiz.grpc.services.vfs.ValidationField.Builder, com.ortiz.grpc.services.vfs.ValidationFieldOrBuilder>(
                verifiedFields_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        verifiedFields_ = null;
      }
      return verifiedFieldsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:services.ValidationFields)
  }

  // @@protoc_insertion_point(class_scope:services.ValidationFields)
  private static final com.ortiz.grpc.services.vfs.ValidationFields DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ortiz.grpc.services.vfs.ValidationFields();
  }

  public static com.ortiz.grpc.services.vfs.ValidationFields getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValidationFields>
      PARSER = new com.google.protobuf.AbstractParser<ValidationFields>() {
    @java.lang.Override
    public ValidationFields parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ValidationFields(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ValidationFields> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValidationFields> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ortiz.grpc.services.vfs.ValidationFields getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

