// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validation-fields-service.proto

package com.ortiz.grpc.services.vfs;

public final class ValidationFieldsServiceOuterClass {
  private ValidationFieldsServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_ValidationFields_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_ValidationFields_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_ValidationField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_ValidationField_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037validation-fields-service.proto\022\010servi" +
      "ces\032\036google/protobuf/wrappers.proto\032\037goo" +
      "gle/protobuf/timestamp.proto\"E\n\020Validati" +
      "onFields\0221\n\016verifiedFields\030\001 \003(\0132\031.servi" +
      "ces.ValidationField\"\353\003\n\017ValidationField\022" +
      "\'\n\002id\030\001 \001(\0132\033.google.protobuf.Int64Value" +
      "\022.\n\010tenantId\030\002 \001(\0132\034.google.protobuf.Str" +
      "ingValue\022.\n\010personId\030\003 \001(\0132\034.google.prot" +
      "obuf.StringValue\022/\n\tfieldName\030\004 \001(\0132\034.go" +
      "ogle.protobuf.StringValue\0220\n\nfieldValue\030" +
      "\005 \001(\0132\034.google.protobuf.StringValue\022*\n\005l" +
      "evel\030\006 \001(\0132\033.google.protobuf.Int32Value\022" +
      "-\n\tvalidated\030\007 \001(\0132\032.google.protobuf.Boo" +
      "lValue\0223\n\017serverValidated\030\010 \001(\0132\032.google" +
      ".protobuf.BoolValue\022+\n\005cause\030\t \001(\0132\034.goo" +
      "gle.protobuf.StringValue\022/\n\013createdDate\030" +
      "\n \001(\0132\032.google.protobuf.Timestamp2\211\002\n\027Va" +
      "lidationFieldsService\022J\n\016ValidateFields\022" +
      "\032.services.ValidationFields\032\032.services.V" +
      "alidationFields\"\000\022N\n\022SaveVerifiedFields\022" +
      "\032.services.ValidationFields\032\032.services.V" +
      "alidationFields\"\000\022R\n\026UndoSaveVerifiedFie" +
      "lds\022\032.services.ValidationFields\032\032.servic" +
      "es.ValidationFields\"\000B\037\n\033com.ortiz.grpc." +
      "services.vfsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_services_ValidationFields_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_services_ValidationFields_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_ValidationFields_descriptor,
        new java.lang.String[] { "VerifiedFields", });
    internal_static_services_ValidationField_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_services_ValidationField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_ValidationField_descriptor,
        new java.lang.String[] { "Id", "TenantId", "PersonId", "FieldName", "FieldValue", "Level", "Validated", "ServerValidated", "Cause", "CreatedDate", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
