// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validation-fields-service.proto

package com.ortiz.grpc.services.vfs;

public interface VerfieldFieldsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.VerfieldFields)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .services.VerifiedField verifiedFields = 1;</code>
   */
  java.util.List<com.ortiz.grpc.services.vfs.VerifiedField> 
      getVerifiedFieldsList();
  /**
   * <code>repeated .services.VerifiedField verifiedFields = 1;</code>
   */
  com.ortiz.grpc.services.vfs.VerifiedField getVerifiedFields(int index);
  /**
   * <code>repeated .services.VerifiedField verifiedFields = 1;</code>
   */
  int getVerifiedFieldsCount();
  /**
   * <code>repeated .services.VerifiedField verifiedFields = 1;</code>
   */
  java.util.List<? extends com.ortiz.grpc.services.vfs.VerifiedFieldOrBuilder> 
      getVerifiedFieldsOrBuilderList();
  /**
   * <code>repeated .services.VerifiedField verifiedFields = 1;</code>
   */
  com.ortiz.grpc.services.vfs.VerifiedFieldOrBuilder getVerifiedFieldsOrBuilder(
      int index);
}
