// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validation-fields-service.proto

package com.ortiz.grpc.services.vfs;

/**
 * Protobuf type {@code services.VerifiedField}
 */
public final class VerifiedField extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:services.VerifiedField)
    VerifiedFieldOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VerifiedField.newBuilder() to construct.
  private VerifiedField(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VerifiedField() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VerifiedField();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VerifiedField(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (id_ != null) {
              subBuilder = id_.toBuilder();
            }
            id_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(id_);
              id_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (tenantId_ != null) {
              subBuilder = tenantId_.toBuilder();
            }
            tenantId_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tenantId_);
              tenantId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (personId_ != null) {
              subBuilder = personId_.toBuilder();
            }
            personId_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(personId_);
              personId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (fieldName_ != null) {
              subBuilder = fieldName_.toBuilder();
            }
            fieldName_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fieldName_);
              fieldName_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (fieldValue_ != null) {
              subBuilder = fieldValue_.toBuilder();
            }
            fieldValue_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fieldValue_);
              fieldValue_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (level_ != null) {
              subBuilder = level_.toBuilder();
            }
            level_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(level_);
              level_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (validated_ != null) {
              subBuilder = validated_.toBuilder();
            }
            validated_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(validated_);
              validated_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (serverValidated_ != null) {
              subBuilder = serverValidated_.toBuilder();
            }
            serverValidated_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(serverValidated_);
              serverValidated_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (cause_ != null) {
              subBuilder = cause_.toBuilder();
            }
            cause_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cause_);
              cause_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (createdDate_ != null) {
              subBuilder = createdDate_.toBuilder();
            }
            createdDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createdDate_);
              createdDate_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ortiz.grpc.services.vfs.ValidationFieldsServiceOuterClass.internal_static_services_VerifiedField_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ortiz.grpc.services.vfs.ValidationFieldsServiceOuterClass.internal_static_services_VerifiedField_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ortiz.grpc.services.vfs.VerifiedField.class, com.ortiz.grpc.services.vfs.VerifiedField.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.google.protobuf.Int64Value id_;
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.google.protobuf.Int64Value getId() {
    return id_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : id_;
  }
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int TENANTID_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue tenantId_;
  /**
   * <code>.google.protobuf.StringValue tenantId = 2;</code>
   * @return Whether the tenantId field is set.
   */
  @java.lang.Override
  public boolean hasTenantId() {
    return tenantId_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue tenantId = 2;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getTenantId() {
    return tenantId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : tenantId_;
  }
  /**
   * <code>.google.protobuf.StringValue tenantId = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getTenantIdOrBuilder() {
    return getTenantId();
  }

  public static final int PERSONID_FIELD_NUMBER = 3;
  private com.google.protobuf.StringValue personId_;
  /**
   * <code>.google.protobuf.StringValue personId = 3;</code>
   * @return Whether the personId field is set.
   */
  @java.lang.Override
  public boolean hasPersonId() {
    return personId_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue personId = 3;</code>
   * @return The personId.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getPersonId() {
    return personId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : personId_;
  }
  /**
   * <code>.google.protobuf.StringValue personId = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getPersonIdOrBuilder() {
    return getPersonId();
  }

  public static final int FIELDNAME_FIELD_NUMBER = 4;
  private com.google.protobuf.StringValue fieldName_;
  /**
   * <code>.google.protobuf.StringValue fieldName = 4;</code>
   * @return Whether the fieldName field is set.
   */
  @java.lang.Override
  public boolean hasFieldName() {
    return fieldName_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue fieldName = 4;</code>
   * @return The fieldName.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getFieldName() {
    return fieldName_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : fieldName_;
  }
  /**
   * <code>.google.protobuf.StringValue fieldName = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getFieldNameOrBuilder() {
    return getFieldName();
  }

  public static final int FIELDVALUE_FIELD_NUMBER = 5;
  private com.google.protobuf.StringValue fieldValue_;
  /**
   * <code>.google.protobuf.StringValue fieldValue = 5;</code>
   * @return Whether the fieldValue field is set.
   */
  @java.lang.Override
  public boolean hasFieldValue() {
    return fieldValue_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue fieldValue = 5;</code>
   * @return The fieldValue.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getFieldValue() {
    return fieldValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : fieldValue_;
  }
  /**
   * <code>.google.protobuf.StringValue fieldValue = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getFieldValueOrBuilder() {
    return getFieldValue();
  }

  public static final int LEVEL_FIELD_NUMBER = 6;
  private com.google.protobuf.Int32Value level_;
  /**
   * <code>.google.protobuf.Int32Value level = 6;</code>
   * @return Whether the level field is set.
   */
  @java.lang.Override
  public boolean hasLevel() {
    return level_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value level = 6;</code>
   * @return The level.
   */
  @java.lang.Override
  public com.google.protobuf.Int32Value getLevel() {
    return level_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : level_;
  }
  /**
   * <code>.google.protobuf.Int32Value level = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int32ValueOrBuilder getLevelOrBuilder() {
    return getLevel();
  }

  public static final int VALIDATED_FIELD_NUMBER = 7;
  private com.google.protobuf.BoolValue validated_;
  /**
   * <code>.google.protobuf.BoolValue validated = 7;</code>
   * @return Whether the validated field is set.
   */
  @java.lang.Override
  public boolean hasValidated() {
    return validated_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue validated = 7;</code>
   * @return The validated.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getValidated() {
    return validated_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : validated_;
  }
  /**
   * <code>.google.protobuf.BoolValue validated = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getValidatedOrBuilder() {
    return getValidated();
  }

  public static final int SERVERVALIDATED_FIELD_NUMBER = 8;
  private com.google.protobuf.BoolValue serverValidated_;
  /**
   * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
   * @return Whether the serverValidated field is set.
   */
  @java.lang.Override
  public boolean hasServerValidated() {
    return serverValidated_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
   * @return The serverValidated.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getServerValidated() {
    return serverValidated_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : serverValidated_;
  }
  /**
   * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getServerValidatedOrBuilder() {
    return getServerValidated();
  }

  public static final int CAUSE_FIELD_NUMBER = 9;
  private com.google.protobuf.StringValue cause_;
  /**
   * <code>.google.protobuf.StringValue cause = 9;</code>
   * @return Whether the cause field is set.
   */
  @java.lang.Override
  public boolean hasCause() {
    return cause_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue cause = 9;</code>
   * @return The cause.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getCause() {
    return cause_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : cause_;
  }
  /**
   * <code>.google.protobuf.StringValue cause = 9;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getCauseOrBuilder() {
    return getCause();
  }

  public static final int CREATEDDATE_FIELD_NUMBER = 10;
  private com.google.protobuf.Timestamp createdDate_;
  /**
   * <code>.google.protobuf.Timestamp createdDate = 10;</code>
   * @return Whether the createdDate field is set.
   */
  @java.lang.Override
  public boolean hasCreatedDate() {
    return createdDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp createdDate = 10;</code>
   * @return The createdDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedDate() {
    return createdDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp createdDate = 10;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedDateOrBuilder() {
    return getCreatedDate();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (tenantId_ != null) {
      output.writeMessage(2, getTenantId());
    }
    if (personId_ != null) {
      output.writeMessage(3, getPersonId());
    }
    if (fieldName_ != null) {
      output.writeMessage(4, getFieldName());
    }
    if (fieldValue_ != null) {
      output.writeMessage(5, getFieldValue());
    }
    if (level_ != null) {
      output.writeMessage(6, getLevel());
    }
    if (validated_ != null) {
      output.writeMessage(7, getValidated());
    }
    if (serverValidated_ != null) {
      output.writeMessage(8, getServerValidated());
    }
    if (cause_ != null) {
      output.writeMessage(9, getCause());
    }
    if (createdDate_ != null) {
      output.writeMessage(10, getCreatedDate());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (tenantId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTenantId());
    }
    if (personId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPersonId());
    }
    if (fieldName_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFieldName());
    }
    if (fieldValue_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getFieldValue());
    }
    if (level_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLevel());
    }
    if (validated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getValidated());
    }
    if (serverValidated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getServerValidated());
    }
    if (cause_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getCause());
    }
    if (createdDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getCreatedDate());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ortiz.grpc.services.vfs.VerifiedField)) {
      return super.equals(obj);
    }
    com.ortiz.grpc.services.vfs.VerifiedField other = (com.ortiz.grpc.services.vfs.VerifiedField) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasTenantId() != other.hasTenantId()) return false;
    if (hasTenantId()) {
      if (!getTenantId()
          .equals(other.getTenantId())) return false;
    }
    if (hasPersonId() != other.hasPersonId()) return false;
    if (hasPersonId()) {
      if (!getPersonId()
          .equals(other.getPersonId())) return false;
    }
    if (hasFieldName() != other.hasFieldName()) return false;
    if (hasFieldName()) {
      if (!getFieldName()
          .equals(other.getFieldName())) return false;
    }
    if (hasFieldValue() != other.hasFieldValue()) return false;
    if (hasFieldValue()) {
      if (!getFieldValue()
          .equals(other.getFieldValue())) return false;
    }
    if (hasLevel() != other.hasLevel()) return false;
    if (hasLevel()) {
      if (!getLevel()
          .equals(other.getLevel())) return false;
    }
    if (hasValidated() != other.hasValidated()) return false;
    if (hasValidated()) {
      if (!getValidated()
          .equals(other.getValidated())) return false;
    }
    if (hasServerValidated() != other.hasServerValidated()) return false;
    if (hasServerValidated()) {
      if (!getServerValidated()
          .equals(other.getServerValidated())) return false;
    }
    if (hasCause() != other.hasCause()) return false;
    if (hasCause()) {
      if (!getCause()
          .equals(other.getCause())) return false;
    }
    if (hasCreatedDate() != other.hasCreatedDate()) return false;
    if (hasCreatedDate()) {
      if (!getCreatedDate()
          .equals(other.getCreatedDate())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasTenantId()) {
      hash = (37 * hash) + TENANTID_FIELD_NUMBER;
      hash = (53 * hash) + getTenantId().hashCode();
    }
    if (hasPersonId()) {
      hash = (37 * hash) + PERSONID_FIELD_NUMBER;
      hash = (53 * hash) + getPersonId().hashCode();
    }
    if (hasFieldName()) {
      hash = (37 * hash) + FIELDNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFieldName().hashCode();
    }
    if (hasFieldValue()) {
      hash = (37 * hash) + FIELDVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getFieldValue().hashCode();
    }
    if (hasLevel()) {
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel().hashCode();
    }
    if (hasValidated()) {
      hash = (37 * hash) + VALIDATED_FIELD_NUMBER;
      hash = (53 * hash) + getValidated().hashCode();
    }
    if (hasServerValidated()) {
      hash = (37 * hash) + SERVERVALIDATED_FIELD_NUMBER;
      hash = (53 * hash) + getServerValidated().hashCode();
    }
    if (hasCause()) {
      hash = (37 * hash) + CAUSE_FIELD_NUMBER;
      hash = (53 * hash) + getCause().hashCode();
    }
    if (hasCreatedDate()) {
      hash = (37 * hash) + CREATEDDATE_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedDate().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ortiz.grpc.services.vfs.VerifiedField parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.vfs.VerifiedField parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.vfs.VerifiedField parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.vfs.VerifiedField parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.vfs.VerifiedField parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ortiz.grpc.services.vfs.VerifiedField parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ortiz.grpc.services.vfs.VerifiedField parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.vfs.VerifiedField parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ortiz.grpc.services.vfs.VerifiedField parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.vfs.VerifiedField parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ortiz.grpc.services.vfs.VerifiedField parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ortiz.grpc.services.vfs.VerifiedField parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ortiz.grpc.services.vfs.VerifiedField prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code services.VerifiedField}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:services.VerifiedField)
      com.ortiz.grpc.services.vfs.VerifiedFieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ortiz.grpc.services.vfs.ValidationFieldsServiceOuterClass.internal_static_services_VerifiedField_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ortiz.grpc.services.vfs.ValidationFieldsServiceOuterClass.internal_static_services_VerifiedField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ortiz.grpc.services.vfs.VerifiedField.class, com.ortiz.grpc.services.vfs.VerifiedField.Builder.class);
    }

    // Construct using com.ortiz.grpc.services.vfs.VerifiedField.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      if (tenantIdBuilder_ == null) {
        tenantId_ = null;
      } else {
        tenantId_ = null;
        tenantIdBuilder_ = null;
      }
      if (personIdBuilder_ == null) {
        personId_ = null;
      } else {
        personId_ = null;
        personIdBuilder_ = null;
      }
      if (fieldNameBuilder_ == null) {
        fieldName_ = null;
      } else {
        fieldName_ = null;
        fieldNameBuilder_ = null;
      }
      if (fieldValueBuilder_ == null) {
        fieldValue_ = null;
      } else {
        fieldValue_ = null;
        fieldValueBuilder_ = null;
      }
      if (levelBuilder_ == null) {
        level_ = null;
      } else {
        level_ = null;
        levelBuilder_ = null;
      }
      if (validatedBuilder_ == null) {
        validated_ = null;
      } else {
        validated_ = null;
        validatedBuilder_ = null;
      }
      if (serverValidatedBuilder_ == null) {
        serverValidated_ = null;
      } else {
        serverValidated_ = null;
        serverValidatedBuilder_ = null;
      }
      if (causeBuilder_ == null) {
        cause_ = null;
      } else {
        cause_ = null;
        causeBuilder_ = null;
      }
      if (createdDateBuilder_ == null) {
        createdDate_ = null;
      } else {
        createdDate_ = null;
        createdDateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ortiz.grpc.services.vfs.ValidationFieldsServiceOuterClass.internal_static_services_VerifiedField_descriptor;
    }

    @java.lang.Override
    public com.ortiz.grpc.services.vfs.VerifiedField getDefaultInstanceForType() {
      return com.ortiz.grpc.services.vfs.VerifiedField.getDefaultInstance();
    }

    @java.lang.Override
    public com.ortiz.grpc.services.vfs.VerifiedField build() {
      com.ortiz.grpc.services.vfs.VerifiedField result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ortiz.grpc.services.vfs.VerifiedField buildPartial() {
      com.ortiz.grpc.services.vfs.VerifiedField result = new com.ortiz.grpc.services.vfs.VerifiedField(this);
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      if (tenantIdBuilder_ == null) {
        result.tenantId_ = tenantId_;
      } else {
        result.tenantId_ = tenantIdBuilder_.build();
      }
      if (personIdBuilder_ == null) {
        result.personId_ = personId_;
      } else {
        result.personId_ = personIdBuilder_.build();
      }
      if (fieldNameBuilder_ == null) {
        result.fieldName_ = fieldName_;
      } else {
        result.fieldName_ = fieldNameBuilder_.build();
      }
      if (fieldValueBuilder_ == null) {
        result.fieldValue_ = fieldValue_;
      } else {
        result.fieldValue_ = fieldValueBuilder_.build();
      }
      if (levelBuilder_ == null) {
        result.level_ = level_;
      } else {
        result.level_ = levelBuilder_.build();
      }
      if (validatedBuilder_ == null) {
        result.validated_ = validated_;
      } else {
        result.validated_ = validatedBuilder_.build();
      }
      if (serverValidatedBuilder_ == null) {
        result.serverValidated_ = serverValidated_;
      } else {
        result.serverValidated_ = serverValidatedBuilder_.build();
      }
      if (causeBuilder_ == null) {
        result.cause_ = cause_;
      } else {
        result.cause_ = causeBuilder_.build();
      }
      if (createdDateBuilder_ == null) {
        result.createdDate_ = createdDate_;
      } else {
        result.createdDate_ = createdDateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ortiz.grpc.services.vfs.VerifiedField) {
        return mergeFrom((com.ortiz.grpc.services.vfs.VerifiedField)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ortiz.grpc.services.vfs.VerifiedField other) {
      if (other == com.ortiz.grpc.services.vfs.VerifiedField.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasTenantId()) {
        mergeTenantId(other.getTenantId());
      }
      if (other.hasPersonId()) {
        mergePersonId(other.getPersonId());
      }
      if (other.hasFieldName()) {
        mergeFieldName(other.getFieldName());
      }
      if (other.hasFieldValue()) {
        mergeFieldValue(other.getFieldValue());
      }
      if (other.hasLevel()) {
        mergeLevel(other.getLevel());
      }
      if (other.hasValidated()) {
        mergeValidated(other.getValidated());
      }
      if (other.hasServerValidated()) {
        mergeServerValidated(other.getServerValidated());
      }
      if (other.hasCause()) {
        mergeCause(other.getCause());
      }
      if (other.hasCreatedDate()) {
        mergeCreatedDate(other.getCreatedDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ortiz.grpc.services.vfs.VerifiedField parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ortiz.grpc.services.vfs.VerifiedField) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int64Value id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> idBuilder_;
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     * @return The id.
     */
    public com.google.protobuf.Int64Value getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder setId(com.google.protobuf.Int64Value value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder setId(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder mergeId(com.google.protobuf.Int64Value value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            com.google.protobuf.Int64Value.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public com.google.protobuf.Int64Value.Builder getIdBuilder() {
      
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private com.google.protobuf.StringValue tenantId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> tenantIdBuilder_;
    /**
     * <code>.google.protobuf.StringValue tenantId = 2;</code>
     * @return Whether the tenantId field is set.
     */
    public boolean hasTenantId() {
      return tenantIdBuilder_ != null || tenantId_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 2;</code>
     * @return The tenantId.
     */
    public com.google.protobuf.StringValue getTenantId() {
      if (tenantIdBuilder_ == null) {
        return tenantId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : tenantId_;
      } else {
        return tenantIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 2;</code>
     */
    public Builder setTenantId(com.google.protobuf.StringValue value) {
      if (tenantIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tenantId_ = value;
        onChanged();
      } else {
        tenantIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 2;</code>
     */
    public Builder setTenantId(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (tenantIdBuilder_ == null) {
        tenantId_ = builderForValue.build();
        onChanged();
      } else {
        tenantIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 2;</code>
     */
    public Builder mergeTenantId(com.google.protobuf.StringValue value) {
      if (tenantIdBuilder_ == null) {
        if (tenantId_ != null) {
          tenantId_ =
            com.google.protobuf.StringValue.newBuilder(tenantId_).mergeFrom(value).buildPartial();
        } else {
          tenantId_ = value;
        }
        onChanged();
      } else {
        tenantIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 2;</code>
     */
    public Builder clearTenantId() {
      if (tenantIdBuilder_ == null) {
        tenantId_ = null;
        onChanged();
      } else {
        tenantId_ = null;
        tenantIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getTenantIdBuilder() {
      
      onChanged();
      return getTenantIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getTenantIdOrBuilder() {
      if (tenantIdBuilder_ != null) {
        return tenantIdBuilder_.getMessageOrBuilder();
      } else {
        return tenantId_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : tenantId_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue tenantId = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getTenantIdFieldBuilder() {
      if (tenantIdBuilder_ == null) {
        tenantIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getTenantId(),
                getParentForChildren(),
                isClean());
        tenantId_ = null;
      }
      return tenantIdBuilder_;
    }

    private com.google.protobuf.StringValue personId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> personIdBuilder_;
    /**
     * <code>.google.protobuf.StringValue personId = 3;</code>
     * @return Whether the personId field is set.
     */
    public boolean hasPersonId() {
      return personIdBuilder_ != null || personId_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 3;</code>
     * @return The personId.
     */
    public com.google.protobuf.StringValue getPersonId() {
      if (personIdBuilder_ == null) {
        return personId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : personId_;
      } else {
        return personIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue personId = 3;</code>
     */
    public Builder setPersonId(com.google.protobuf.StringValue value) {
      if (personIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        personId_ = value;
        onChanged();
      } else {
        personIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 3;</code>
     */
    public Builder setPersonId(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (personIdBuilder_ == null) {
        personId_ = builderForValue.build();
        onChanged();
      } else {
        personIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 3;</code>
     */
    public Builder mergePersonId(com.google.protobuf.StringValue value) {
      if (personIdBuilder_ == null) {
        if (personId_ != null) {
          personId_ =
            com.google.protobuf.StringValue.newBuilder(personId_).mergeFrom(value).buildPartial();
        } else {
          personId_ = value;
        }
        onChanged();
      } else {
        personIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 3;</code>
     */
    public Builder clearPersonId() {
      if (personIdBuilder_ == null) {
        personId_ = null;
        onChanged();
      } else {
        personId_ = null;
        personIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue personId = 3;</code>
     */
    public com.google.protobuf.StringValue.Builder getPersonIdBuilder() {
      
      onChanged();
      return getPersonIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue personId = 3;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getPersonIdOrBuilder() {
      if (personIdBuilder_ != null) {
        return personIdBuilder_.getMessageOrBuilder();
      } else {
        return personId_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : personId_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue personId = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getPersonIdFieldBuilder() {
      if (personIdBuilder_ == null) {
        personIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getPersonId(),
                getParentForChildren(),
                isClean());
        personId_ = null;
      }
      return personIdBuilder_;
    }

    private com.google.protobuf.StringValue fieldName_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> fieldNameBuilder_;
    /**
     * <code>.google.protobuf.StringValue fieldName = 4;</code>
     * @return Whether the fieldName field is set.
     */
    public boolean hasFieldName() {
      return fieldNameBuilder_ != null || fieldName_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue fieldName = 4;</code>
     * @return The fieldName.
     */
    public com.google.protobuf.StringValue getFieldName() {
      if (fieldNameBuilder_ == null) {
        return fieldName_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : fieldName_;
      } else {
        return fieldNameBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue fieldName = 4;</code>
     */
    public Builder setFieldName(com.google.protobuf.StringValue value) {
      if (fieldNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fieldName_ = value;
        onChanged();
      } else {
        fieldNameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fieldName = 4;</code>
     */
    public Builder setFieldName(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (fieldNameBuilder_ == null) {
        fieldName_ = builderForValue.build();
        onChanged();
      } else {
        fieldNameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fieldName = 4;</code>
     */
    public Builder mergeFieldName(com.google.protobuf.StringValue value) {
      if (fieldNameBuilder_ == null) {
        if (fieldName_ != null) {
          fieldName_ =
            com.google.protobuf.StringValue.newBuilder(fieldName_).mergeFrom(value).buildPartial();
        } else {
          fieldName_ = value;
        }
        onChanged();
      } else {
        fieldNameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fieldName = 4;</code>
     */
    public Builder clearFieldName() {
      if (fieldNameBuilder_ == null) {
        fieldName_ = null;
        onChanged();
      } else {
        fieldName_ = null;
        fieldNameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fieldName = 4;</code>
     */
    public com.google.protobuf.StringValue.Builder getFieldNameBuilder() {
      
      onChanged();
      return getFieldNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue fieldName = 4;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getFieldNameOrBuilder() {
      if (fieldNameBuilder_ != null) {
        return fieldNameBuilder_.getMessageOrBuilder();
      } else {
        return fieldName_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : fieldName_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue fieldName = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getFieldNameFieldBuilder() {
      if (fieldNameBuilder_ == null) {
        fieldNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getFieldName(),
                getParentForChildren(),
                isClean());
        fieldName_ = null;
      }
      return fieldNameBuilder_;
    }

    private com.google.protobuf.StringValue fieldValue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> fieldValueBuilder_;
    /**
     * <code>.google.protobuf.StringValue fieldValue = 5;</code>
     * @return Whether the fieldValue field is set.
     */
    public boolean hasFieldValue() {
      return fieldValueBuilder_ != null || fieldValue_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue fieldValue = 5;</code>
     * @return The fieldValue.
     */
    public com.google.protobuf.StringValue getFieldValue() {
      if (fieldValueBuilder_ == null) {
        return fieldValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : fieldValue_;
      } else {
        return fieldValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue fieldValue = 5;</code>
     */
    public Builder setFieldValue(com.google.protobuf.StringValue value) {
      if (fieldValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fieldValue_ = value;
        onChanged();
      } else {
        fieldValueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fieldValue = 5;</code>
     */
    public Builder setFieldValue(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (fieldValueBuilder_ == null) {
        fieldValue_ = builderForValue.build();
        onChanged();
      } else {
        fieldValueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fieldValue = 5;</code>
     */
    public Builder mergeFieldValue(com.google.protobuf.StringValue value) {
      if (fieldValueBuilder_ == null) {
        if (fieldValue_ != null) {
          fieldValue_ =
            com.google.protobuf.StringValue.newBuilder(fieldValue_).mergeFrom(value).buildPartial();
        } else {
          fieldValue_ = value;
        }
        onChanged();
      } else {
        fieldValueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fieldValue = 5;</code>
     */
    public Builder clearFieldValue() {
      if (fieldValueBuilder_ == null) {
        fieldValue_ = null;
        onChanged();
      } else {
        fieldValue_ = null;
        fieldValueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fieldValue = 5;</code>
     */
    public com.google.protobuf.StringValue.Builder getFieldValueBuilder() {
      
      onChanged();
      return getFieldValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue fieldValue = 5;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getFieldValueOrBuilder() {
      if (fieldValueBuilder_ != null) {
        return fieldValueBuilder_.getMessageOrBuilder();
      } else {
        return fieldValue_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : fieldValue_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue fieldValue = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getFieldValueFieldBuilder() {
      if (fieldValueBuilder_ == null) {
        fieldValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getFieldValue(),
                getParentForChildren(),
                isClean());
        fieldValue_ = null;
      }
      return fieldValueBuilder_;
    }

    private com.google.protobuf.Int32Value level_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> levelBuilder_;
    /**
     * <code>.google.protobuf.Int32Value level = 6;</code>
     * @return Whether the level field is set.
     */
    public boolean hasLevel() {
      return levelBuilder_ != null || level_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value level = 6;</code>
     * @return The level.
     */
    public com.google.protobuf.Int32Value getLevel() {
      if (levelBuilder_ == null) {
        return level_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : level_;
      } else {
        return levelBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value level = 6;</code>
     */
    public Builder setLevel(com.google.protobuf.Int32Value value) {
      if (levelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        level_ = value;
        onChanged();
      } else {
        levelBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value level = 6;</code>
     */
    public Builder setLevel(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (levelBuilder_ == null) {
        level_ = builderForValue.build();
        onChanged();
      } else {
        levelBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value level = 6;</code>
     */
    public Builder mergeLevel(com.google.protobuf.Int32Value value) {
      if (levelBuilder_ == null) {
        if (level_ != null) {
          level_ =
            com.google.protobuf.Int32Value.newBuilder(level_).mergeFrom(value).buildPartial();
        } else {
          level_ = value;
        }
        onChanged();
      } else {
        levelBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value level = 6;</code>
     */
    public Builder clearLevel() {
      if (levelBuilder_ == null) {
        level_ = null;
        onChanged();
      } else {
        level_ = null;
        levelBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value level = 6;</code>
     */
    public com.google.protobuf.Int32Value.Builder getLevelBuilder() {
      
      onChanged();
      return getLevelFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value level = 6;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getLevelOrBuilder() {
      if (levelBuilder_ != null) {
        return levelBuilder_.getMessageOrBuilder();
      } else {
        return level_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : level_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value level = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getLevelFieldBuilder() {
      if (levelBuilder_ == null) {
        levelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getLevel(),
                getParentForChildren(),
                isClean());
        level_ = null;
      }
      return levelBuilder_;
    }

    private com.google.protobuf.BoolValue validated_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> validatedBuilder_;
    /**
     * <code>.google.protobuf.BoolValue validated = 7;</code>
     * @return Whether the validated field is set.
     */
    public boolean hasValidated() {
      return validatedBuilder_ != null || validated_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue validated = 7;</code>
     * @return The validated.
     */
    public com.google.protobuf.BoolValue getValidated() {
      if (validatedBuilder_ == null) {
        return validated_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : validated_;
      } else {
        return validatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue validated = 7;</code>
     */
    public Builder setValidated(com.google.protobuf.BoolValue value) {
      if (validatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        validated_ = value;
        onChanged();
      } else {
        validatedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue validated = 7;</code>
     */
    public Builder setValidated(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (validatedBuilder_ == null) {
        validated_ = builderForValue.build();
        onChanged();
      } else {
        validatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue validated = 7;</code>
     */
    public Builder mergeValidated(com.google.protobuf.BoolValue value) {
      if (validatedBuilder_ == null) {
        if (validated_ != null) {
          validated_ =
            com.google.protobuf.BoolValue.newBuilder(validated_).mergeFrom(value).buildPartial();
        } else {
          validated_ = value;
        }
        onChanged();
      } else {
        validatedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue validated = 7;</code>
     */
    public Builder clearValidated() {
      if (validatedBuilder_ == null) {
        validated_ = null;
        onChanged();
      } else {
        validated_ = null;
        validatedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue validated = 7;</code>
     */
    public com.google.protobuf.BoolValue.Builder getValidatedBuilder() {
      
      onChanged();
      return getValidatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue validated = 7;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getValidatedOrBuilder() {
      if (validatedBuilder_ != null) {
        return validatedBuilder_.getMessageOrBuilder();
      } else {
        return validated_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : validated_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue validated = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getValidatedFieldBuilder() {
      if (validatedBuilder_ == null) {
        validatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getValidated(),
                getParentForChildren(),
                isClean());
        validated_ = null;
      }
      return validatedBuilder_;
    }

    private com.google.protobuf.BoolValue serverValidated_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> serverValidatedBuilder_;
    /**
     * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
     * @return Whether the serverValidated field is set.
     */
    public boolean hasServerValidated() {
      return serverValidatedBuilder_ != null || serverValidated_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
     * @return The serverValidated.
     */
    public com.google.protobuf.BoolValue getServerValidated() {
      if (serverValidatedBuilder_ == null) {
        return serverValidated_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : serverValidated_;
      } else {
        return serverValidatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
     */
    public Builder setServerValidated(com.google.protobuf.BoolValue value) {
      if (serverValidatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        serverValidated_ = value;
        onChanged();
      } else {
        serverValidatedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
     */
    public Builder setServerValidated(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (serverValidatedBuilder_ == null) {
        serverValidated_ = builderForValue.build();
        onChanged();
      } else {
        serverValidatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
     */
    public Builder mergeServerValidated(com.google.protobuf.BoolValue value) {
      if (serverValidatedBuilder_ == null) {
        if (serverValidated_ != null) {
          serverValidated_ =
            com.google.protobuf.BoolValue.newBuilder(serverValidated_).mergeFrom(value).buildPartial();
        } else {
          serverValidated_ = value;
        }
        onChanged();
      } else {
        serverValidatedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
     */
    public Builder clearServerValidated() {
      if (serverValidatedBuilder_ == null) {
        serverValidated_ = null;
        onChanged();
      } else {
        serverValidated_ = null;
        serverValidatedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
     */
    public com.google.protobuf.BoolValue.Builder getServerValidatedBuilder() {
      
      onChanged();
      return getServerValidatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getServerValidatedOrBuilder() {
      if (serverValidatedBuilder_ != null) {
        return serverValidatedBuilder_.getMessageOrBuilder();
      } else {
        return serverValidated_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : serverValidated_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue serverValidated = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getServerValidatedFieldBuilder() {
      if (serverValidatedBuilder_ == null) {
        serverValidatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getServerValidated(),
                getParentForChildren(),
                isClean());
        serverValidated_ = null;
      }
      return serverValidatedBuilder_;
    }

    private com.google.protobuf.StringValue cause_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> causeBuilder_;
    /**
     * <code>.google.protobuf.StringValue cause = 9;</code>
     * @return Whether the cause field is set.
     */
    public boolean hasCause() {
      return causeBuilder_ != null || cause_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue cause = 9;</code>
     * @return The cause.
     */
    public com.google.protobuf.StringValue getCause() {
      if (causeBuilder_ == null) {
        return cause_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : cause_;
      } else {
        return causeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue cause = 9;</code>
     */
    public Builder setCause(com.google.protobuf.StringValue value) {
      if (causeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cause_ = value;
        onChanged();
      } else {
        causeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cause = 9;</code>
     */
    public Builder setCause(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (causeBuilder_ == null) {
        cause_ = builderForValue.build();
        onChanged();
      } else {
        causeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cause = 9;</code>
     */
    public Builder mergeCause(com.google.protobuf.StringValue value) {
      if (causeBuilder_ == null) {
        if (cause_ != null) {
          cause_ =
            com.google.protobuf.StringValue.newBuilder(cause_).mergeFrom(value).buildPartial();
        } else {
          cause_ = value;
        }
        onChanged();
      } else {
        causeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cause = 9;</code>
     */
    public Builder clearCause() {
      if (causeBuilder_ == null) {
        cause_ = null;
        onChanged();
      } else {
        cause_ = null;
        causeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue cause = 9;</code>
     */
    public com.google.protobuf.StringValue.Builder getCauseBuilder() {
      
      onChanged();
      return getCauseFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue cause = 9;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getCauseOrBuilder() {
      if (causeBuilder_ != null) {
        return causeBuilder_.getMessageOrBuilder();
      } else {
        return cause_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : cause_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue cause = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getCauseFieldBuilder() {
      if (causeBuilder_ == null) {
        causeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getCause(),
                getParentForChildren(),
                isClean());
        cause_ = null;
      }
      return causeBuilder_;
    }

    private com.google.protobuf.Timestamp createdDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp createdDate = 10;</code>
     * @return Whether the createdDate field is set.
     */
    public boolean hasCreatedDate() {
      return createdDateBuilder_ != null || createdDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 10;</code>
     * @return The createdDate.
     */
    public com.google.protobuf.Timestamp getCreatedDate() {
      if (createdDateBuilder_ == null) {
        return createdDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdDate_;
      } else {
        return createdDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 10;</code>
     */
    public Builder setCreatedDate(com.google.protobuf.Timestamp value) {
      if (createdDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdDate_ = value;
        onChanged();
      } else {
        createdDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 10;</code>
     */
    public Builder setCreatedDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdDateBuilder_ == null) {
        createdDate_ = builderForValue.build();
        onChanged();
      } else {
        createdDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 10;</code>
     */
    public Builder mergeCreatedDate(com.google.protobuf.Timestamp value) {
      if (createdDateBuilder_ == null) {
        if (createdDate_ != null) {
          createdDate_ =
            com.google.protobuf.Timestamp.newBuilder(createdDate_).mergeFrom(value).buildPartial();
        } else {
          createdDate_ = value;
        }
        onChanged();
      } else {
        createdDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 10;</code>
     */
    public Builder clearCreatedDate() {
      if (createdDateBuilder_ == null) {
        createdDate_ = null;
        onChanged();
      } else {
        createdDate_ = null;
        createdDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 10;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedDateBuilder() {
      
      onChanged();
      return getCreatedDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 10;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedDateOrBuilder() {
      if (createdDateBuilder_ != null) {
        return createdDateBuilder_.getMessageOrBuilder();
      } else {
        return createdDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedDateFieldBuilder() {
      if (createdDateBuilder_ == null) {
        createdDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedDate(),
                getParentForChildren(),
                isClean());
        createdDate_ = null;
      }
      return createdDateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:services.VerifiedField)
  }

  // @@protoc_insertion_point(class_scope:services.VerifiedField)
  private static final com.ortiz.grpc.services.vfs.VerifiedField DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ortiz.grpc.services.vfs.VerifiedField();
  }

  public static com.ortiz.grpc.services.vfs.VerifiedField getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerifiedField>
      PARSER = new com.google.protobuf.AbstractParser<VerifiedField>() {
    @java.lang.Override
    public VerifiedField parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VerifiedField(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VerifiedField> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerifiedField> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ortiz.grpc.services.vfs.VerifiedField getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

