// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validation-fields-service.proto

package com.ortiz.grpc.services.vfs;

public interface VerifiedFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.VerifiedField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string tenantId = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenantId = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string personId = 3;</code>
   * @return The personId.
   */
  java.lang.String getPersonId();
  /**
   * <code>string personId = 3;</code>
   * @return The bytes for personId.
   */
  com.google.protobuf.ByteString
      getPersonIdBytes();

  /**
   * <code>string fieldName = 4;</code>
   * @return The fieldName.
   */
  java.lang.String getFieldName();
  /**
   * <code>string fieldName = 4;</code>
   * @return The bytes for fieldName.
   */
  com.google.protobuf.ByteString
      getFieldNameBytes();

  /**
   * <code>string fieldValue = 5;</code>
   * @return The fieldValue.
   */
  java.lang.String getFieldValue();
  /**
   * <code>string fieldValue = 5;</code>
   * @return The bytes for fieldValue.
   */
  com.google.protobuf.ByteString
      getFieldValueBytes();

  /**
   * <code>int32 level = 6;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>bool validated = 7;</code>
   * @return The validated.
   */
  boolean getValidated();

  /**
   * <code>.google.protobuf.Timestamp createdDate = 8;</code>
   * @return Whether the createdDate field is set.
   */
  boolean hasCreatedDate();
  /**
   * <code>.google.protobuf.Timestamp createdDate = 8;</code>
   * @return The createdDate.
   */
  com.google.protobuf.Timestamp getCreatedDate();
  /**
   * <code>.google.protobuf.Timestamp createdDate = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedDateOrBuilder();
}
