export const FETCH_END = 'setArticles'
export const FETCH_START = 'setLoading'
export const PURGE_AUTH = 'logOut'
export const SET_AUTH = 'setUser'
export const SET_ERROR = 'setError'
export const SET_VALIDATION_ERROR = 'setValidationError'
export const SET_PROFILE = 'setProfile'
export const RESET_STATE = 'resetModuleState'
