// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/data-service.proto

package com.ortiz.grpc.services.ds;

/**
 * Protobuf type {@code services.Phone}
 */
public final class Phone extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:services.Phone)
    PhoneOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Phone.newBuilder() to construct.
  private Phone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Phone() {
    id_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Phone();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Phone(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 16: {

            ddi_ = input.readInt32();
            break;
          }
          case 24: {

            ddd_ = input.readInt32();
            break;
          }
          case 32: {

            number_ = input.readInt32();
            break;
          }
          case 40: {

            extensionLine_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DataServiceOuterClass.internal_static_services_Phone_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DataServiceOuterClass.internal_static_services_Phone_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Phone.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @Override
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DDI_FIELD_NUMBER = 2;
  private int ddi_;
  /**
   * <code>int32 ddi = 2;</code>
   * @return The ddi.
   */
  @Override
  public int getDdi() {
    return ddi_;
  }

  public static final int DDD_FIELD_NUMBER = 3;
  private int ddd_;
  /**
   * <code>int32 ddd = 3;</code>
   * @return The ddd.
   */
  @Override
  public int getDdd() {
    return ddd_;
  }

  public static final int NUMBER_FIELD_NUMBER = 4;
  private int number_;
  /**
   * <code>int32 number = 4;</code>
   * @return The number.
   */
  @Override
  public int getNumber() {
    return number_;
  }

  public static final int EXTENSIONLINE_FIELD_NUMBER = 5;
  private int extensionLine_;
  /**
   * <code>int32 extensionLine = 5;</code>
   * @return The extensionLine.
   */
  @Override
  public int getExtensionLine() {
    return extensionLine_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (ddi_ != 0) {
      output.writeInt32(2, ddi_);
    }
    if (ddd_ != 0) {
      output.writeInt32(3, ddd_);
    }
    if (number_ != 0) {
      output.writeInt32(4, number_);
    }
    if (extensionLine_ != 0) {
      output.writeInt32(5, extensionLine_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (ddi_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, ddi_);
    }
    if (ddd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, ddd_);
    }
    if (number_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, number_);
    }
    if (extensionLine_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, extensionLine_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Phone)) {
      return super.equals(obj);
    }
    Phone other = (Phone) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (getDdi()
        != other.getDdi()) return false;
    if (getDdd()
        != other.getDdd()) return false;
    if (getNumber()
        != other.getNumber()) return false;
    if (getExtensionLine()
        != other.getExtensionLine()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + DDI_FIELD_NUMBER;
    hash = (53 * hash) + getDdi();
    hash = (37 * hash) + DDD_FIELD_NUMBER;
    hash = (53 * hash) + getDdd();
    hash = (37 * hash) + NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getNumber();
    hash = (37 * hash) + EXTENSIONLINE_FIELD_NUMBER;
    hash = (53 * hash) + getExtensionLine();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Phone parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Phone parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Phone parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Phone parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Phone parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Phone parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Phone parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Phone parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Phone parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Phone parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Phone parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Phone parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Phone prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code services.Phone}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:services.Phone)
      PhoneOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataServiceOuterClass.internal_static_services_Phone_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataServiceOuterClass.internal_static_services_Phone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Phone.class, Builder.class);
    }

    // Construct using com.ortiz.grpc.services.ds.Phone.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = "";

      ddi_ = 0;

      ddd_ = 0;

      number_ = 0;

      extensionLine_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DataServiceOuterClass.internal_static_services_Phone_descriptor;
    }

    @Override
    public Phone getDefaultInstanceForType() {
      return Phone.getDefaultInstance();
    }

    @Override
    public Phone build() {
      Phone result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Phone buildPartial() {
      Phone result = new Phone(this);
      result.id_ = id_;
      result.ddi_ = ddi_;
      result.ddd_ = ddd_;
      result.number_ = number_;
      result.extensionLine_ = extensionLine_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Phone) {
        return mergeFrom((Phone)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Phone other) {
      if (other == Phone.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.getDdi() != 0) {
        setDdi(other.getDdi());
      }
      if (other.getDdd() != 0) {
        setDdd(other.getDdd());
      }
      if (other.getNumber() != 0) {
        setNumber(other.getNumber());
      }
      if (other.getExtensionLine() != 0) {
        setExtensionLine(other.getExtensionLine());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Phone parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Phone) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private int ddi_ ;
    /**
     * <code>int32 ddi = 2;</code>
     * @return The ddi.
     */
    @Override
    public int getDdi() {
      return ddi_;
    }
    /**
     * <code>int32 ddi = 2;</code>
     * @param value The ddi to set.
     * @return This builder for chaining.
     */
    public Builder setDdi(int value) {
      
      ddi_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ddi = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDdi() {
      
      ddi_ = 0;
      onChanged();
      return this;
    }

    private int ddd_ ;
    /**
     * <code>int32 ddd = 3;</code>
     * @return The ddd.
     */
    @Override
    public int getDdd() {
      return ddd_;
    }
    /**
     * <code>int32 ddd = 3;</code>
     * @param value The ddd to set.
     * @return This builder for chaining.
     */
    public Builder setDdd(int value) {
      
      ddd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ddd = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDdd() {
      
      ddd_ = 0;
      onChanged();
      return this;
    }

    private int number_ ;
    /**
     * <code>int32 number = 4;</code>
     * @return The number.
     */
    @Override
    public int getNumber() {
      return number_;
    }
    /**
     * <code>int32 number = 4;</code>
     * @param value The number to set.
     * @return This builder for chaining.
     */
    public Builder setNumber(int value) {
      
      number_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 number = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumber() {
      
      number_ = 0;
      onChanged();
      return this;
    }

    private int extensionLine_ ;
    /**
     * <code>int32 extensionLine = 5;</code>
     * @return The extensionLine.
     */
    @Override
    public int getExtensionLine() {
      return extensionLine_;
    }
    /**
     * <code>int32 extensionLine = 5;</code>
     * @param value The extensionLine to set.
     * @return This builder for chaining.
     */
    public Builder setExtensionLine(int value) {
      
      extensionLine_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 extensionLine = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtensionLine() {
      
      extensionLine_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:services.Phone)
  }

  // @@protoc_insertion_point(class_scope:services.Phone)
  private static final Phone DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Phone();
  }

  public static Phone getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Phone>
      PARSER = new com.google.protobuf.AbstractParser<Phone>() {
    @Override
    public Phone parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Phone(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Phone> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Phone> getParserForType() {
    return PARSER;
  }

  @Override
  public Phone getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

