##################################################################################################
# Data Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: data-service-svc
  labels:    
    service: data-service-svc
spec:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: tcp
  selector:
    app: data-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-v1
  labels:
    app: data-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
      version: v1
  template:
    metadata:
      labels:
        app: data-service
        version: v1
    spec:
      containers:
        - name: data-service
          image: docker.io/tentativafc/poc-data-service:1.0.0-snapshot
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9090
          securityContext:
            runAsUser: 1000
          env:
            - name: MYSQL_HOST
              value: mysql-data-service-svc
            - name: "MYSQL_PORT"
              value: "3306"
            - name: MYSQL_USER
              value: "poc_user"
            - name: MYSQL_PASSWORD
              value: "123456"
            - name: SERVICE_DISCOVERY_HOST
              value: "service-discovery-svc"
            - name: SERVICE_DISCOVERY_PORT
              value: "8500"
---