##################################################################################################
# Orquestrator Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: queue-service-svc
  labels:
    app: queue-service
    service: queue-service-svc
spec:
  ports:
    - port: 5672
      name: client
    - port: 15672
      name: management

  selector:
    app: queue-service-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-service-v1
  labels:
    app: queue-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-service
      version: v1
  template:
    metadata:
      labels:
        app: queue-service
        version: v1
    spec:
      containers:
        - name: rabbit-queue-service
          image: docker.io/rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "poc_user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: orquestrator-service-svc
  labels:
    app: orquestrator-service
    service: orquestrator-service-svc
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: orquestrator-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orquestrator-service-v1
  labels:
    app: orquestrator-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orquestrator-service
      version: v1
  template:
    metadata:
      labels:
        app: orquestrator-service
        version: v1
    spec:
      containers:
        - name: orquestrator-service
          image: docker.io/tentativafc/poc-orchestrator-service:1.0.0-snapshot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_DISCOVERY_HOST
              value: "service-discovery-svc"
            - name: SERVICE_DISCOVERY_PORT
              value: "8500"
            - name: DATA_SERVICE_GRPC_ADDRESS
              value: "discovery:///data-service"
            - name: VALIDATION_FIELDS_SERVICE_GRPC_ADDRESS
              value: "discovery:///validation-fields-service"
            - name: URL_DATA_SERVICE
              value: "http://data-service-svc:8080"
            - name: URL_VALIDATION_FIELDS_SERVICE
              value: "http://validation-service-svc:8080"
            - name: QUEUE_SERVICE_HOST
              value: "queue-service-svc"
            - name: QUEUE_SERVICE_PORT
              value: "5672"
            - name: QUEUE_SERVICE_USER
              value: "poc_user"
            - name: QUEUE_SERVICE_USER_PASS
              value: "123456"
---

