##################################################################################################
# Validation Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: validation-service-svc
  labels:
    service: validation-service-svc
spec:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: grpc
  selector:
    app: validation-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-service-v1
  labels:
    app: validation-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation-service
      version: v1
  template:
    metadata:
      labels:
        app: validation-service
        version: v1
    spec:
      containers:
        - name: validation-service
          image: docker.io/tentativafc/poc-validation-fields-service:1.0.0-snapshot
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: MYSQL_HOST_VALIDATION
              value: "mysql-validation-service-svc"
            - name: MYSQL_PORT_VALIDATION
              value: "3306"
            - name: MYSQL_USER_VALIDATION
              value: "poc_user"
            - name: MYSQL_PASSWORD_VALIDATION
              value: "123456"
            - name: SERVICE_DISCOVERY_HOST
              value: "service-discovery-svc"
            - name: SERVICE_DISCOVERY_PORT
              value: "8500"
            - name: DATA_SERVICE_GRPC_ADDRESS
              value: "discovery://service-discovery-svc:8500/data-service"
---

