package com.ortiz.com.ortiz.business;

public enum StateEnum {
    DO_VALIDATE_FIELDS,
    DO_VALIDATE_PERSON_DATA,
    DO_PERSIST_PERSON,
    DO_PERSIST_VALIDATED_FIELDS,
    DONE,
    UNDO_PERSIST_PERSON,
    UNDO_PERSIST_VALIDATED_FIELDS,
    UNDONE;
}
