// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/validation-fields-service.proto

package com.ortiz.grpc.services.vfs;

/**
 * Protobuf type {@code services.VerifiedField}
 */
public final class VerifiedField extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:services.VerifiedField)
    VerifiedFieldOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VerifiedField.newBuilder() to construct.
  private VerifiedField(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VerifiedField() {
    tenantId_ = "";
    personId_ = "";
    fieldName_ = "";
    fieldValue_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new VerifiedField();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VerifiedField(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            tenantId_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            personId_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            fieldName_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            fieldValue_ = s;
            break;
          }
          case 48: {

            level_ = input.readInt32();
            break;
          }
          case 56: {

            validated_ = input.readBool();
            break;
          }
          case 66: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (createdDate_ != null) {
              subBuilder = createdDate_.toBuilder();
            }
            createdDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createdDate_);
              createdDate_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ValidationFieldsServiceOuterClass.internal_static_services_VerifiedField_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ValidationFieldsServiceOuterClass.internal_static_services_VerifiedField_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            VerifiedField.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @Override
  public long getId() {
    return id_;
  }

  public static final int TENANTID_FIELD_NUMBER = 2;
  private volatile Object tenantId_;
  /**
   * <code>string tenantId = 2;</code>
   * @return The tenantId.
   */
  @Override
  public String getTenantId() {
    Object ref = tenantId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenantId = 2;</code>
   * @return The bytes for tenantId.
   */
  @Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    Object ref = tenantId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERSONID_FIELD_NUMBER = 3;
  private volatile Object personId_;
  /**
   * <code>string personId = 3;</code>
   * @return The personId.
   */
  @Override
  public String getPersonId() {
    Object ref = personId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      personId_ = s;
      return s;
    }
  }
  /**
   * <code>string personId = 3;</code>
   * @return The bytes for personId.
   */
  @Override
  public com.google.protobuf.ByteString
      getPersonIdBytes() {
    Object ref = personId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      personId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELDNAME_FIELD_NUMBER = 4;
  private volatile Object fieldName_;
  /**
   * <code>string fieldName = 4;</code>
   * @return The fieldName.
   */
  @Override
  public String getFieldName() {
    Object ref = fieldName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fieldName_ = s;
      return s;
    }
  }
  /**
   * <code>string fieldName = 4;</code>
   * @return The bytes for fieldName.
   */
  @Override
  public com.google.protobuf.ByteString
      getFieldNameBytes() {
    Object ref = fieldName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fieldName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELDVALUE_FIELD_NUMBER = 5;
  private volatile Object fieldValue_;
  /**
   * <code>string fieldValue = 5;</code>
   * @return The fieldValue.
   */
  @Override
  public String getFieldValue() {
    Object ref = fieldValue_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fieldValue_ = s;
      return s;
    }
  }
  /**
   * <code>string fieldValue = 5;</code>
   * @return The bytes for fieldValue.
   */
  @Override
  public com.google.protobuf.ByteString
      getFieldValueBytes() {
    Object ref = fieldValue_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fieldValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEVEL_FIELD_NUMBER = 6;
  private int level_;
  /**
   * <code>int32 level = 6;</code>
   * @return The level.
   */
  @Override
  public int getLevel() {
    return level_;
  }

  public static final int VALIDATED_FIELD_NUMBER = 7;
  private boolean validated_;
  /**
   * <code>bool validated = 7;</code>
   * @return The validated.
   */
  @Override
  public boolean getValidated() {
    return validated_;
  }

  public static final int CREATEDDATE_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp createdDate_;
  /**
   * <code>.google.protobuf.Timestamp createdDate = 8;</code>
   * @return Whether the createdDate field is set.
   */
  @Override
  public boolean hasCreatedDate() {
    return createdDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp createdDate = 8;</code>
   * @return The createdDate.
   */
  @Override
  public com.google.protobuf.Timestamp getCreatedDate() {
    return createdDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp createdDate = 8;</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getCreatedDateOrBuilder() {
    return getCreatedDate();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getTenantIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tenantId_);
    }
    if (!getPersonIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, personId_);
    }
    if (!getFieldNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fieldName_);
    }
    if (!getFieldValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fieldValue_);
    }
    if (level_ != 0) {
      output.writeInt32(6, level_);
    }
    if (validated_ != false) {
      output.writeBool(7, validated_);
    }
    if (createdDate_ != null) {
      output.writeMessage(8, getCreatedDate());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getTenantIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tenantId_);
    }
    if (!getPersonIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, personId_);
    }
    if (!getFieldNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fieldName_);
    }
    if (!getFieldValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fieldValue_);
    }
    if (level_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, level_);
    }
    if (validated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, validated_);
    }
    if (createdDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getCreatedDate());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof VerifiedField)) {
      return super.equals(obj);
    }
    VerifiedField other = (VerifiedField) obj;

    if (getId()
        != other.getId()) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getPersonId()
        .equals(other.getPersonId())) return false;
    if (!getFieldName()
        .equals(other.getFieldName())) return false;
    if (!getFieldValue()
        .equals(other.getFieldValue())) return false;
    if (getLevel()
        != other.getLevel()) return false;
    if (getValidated()
        != other.getValidated()) return false;
    if (hasCreatedDate() != other.hasCreatedDate()) return false;
    if (hasCreatedDate()) {
      if (!getCreatedDate()
          .equals(other.getCreatedDate())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + TENANTID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + PERSONID_FIELD_NUMBER;
    hash = (53 * hash) + getPersonId().hashCode();
    hash = (37 * hash) + FIELDNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFieldName().hashCode();
    hash = (37 * hash) + FIELDVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getFieldValue().hashCode();
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLevel();
    hash = (37 * hash) + VALIDATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getValidated());
    if (hasCreatedDate()) {
      hash = (37 * hash) + CREATEDDATE_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedDate().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VerifiedField parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VerifiedField parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VerifiedField parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VerifiedField parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VerifiedField parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VerifiedField parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VerifiedField parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VerifiedField parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static VerifiedField parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static VerifiedField parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static VerifiedField parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VerifiedField parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(VerifiedField prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code services.VerifiedField}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:services.VerifiedField)
      VerifiedFieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ValidationFieldsServiceOuterClass.internal_static_services_VerifiedField_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ValidationFieldsServiceOuterClass.internal_static_services_VerifiedField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VerifiedField.class, Builder.class);
    }

    // Construct using com.ortiz.grpc.services.vfs.VerifiedField.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      tenantId_ = "";

      personId_ = "";

      fieldName_ = "";

      fieldValue_ = "";

      level_ = 0;

      validated_ = false;

      if (createdDateBuilder_ == null) {
        createdDate_ = null;
      } else {
        createdDate_ = null;
        createdDateBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ValidationFieldsServiceOuterClass.internal_static_services_VerifiedField_descriptor;
    }

    @Override
    public VerifiedField getDefaultInstanceForType() {
      return VerifiedField.getDefaultInstance();
    }

    @Override
    public VerifiedField build() {
      VerifiedField result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public VerifiedField buildPartial() {
      VerifiedField result = new VerifiedField(this);
      result.id_ = id_;
      result.tenantId_ = tenantId_;
      result.personId_ = personId_;
      result.fieldName_ = fieldName_;
      result.fieldValue_ = fieldValue_;
      result.level_ = level_;
      result.validated_ = validated_;
      if (createdDateBuilder_ == null) {
        result.createdDate_ = createdDate_;
      } else {
        result.createdDate_ = createdDateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VerifiedField) {
        return mergeFrom((VerifiedField)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VerifiedField other) {
      if (other == VerifiedField.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        onChanged();
      }
      if (!other.getPersonId().isEmpty()) {
        personId_ = other.personId_;
        onChanged();
      }
      if (!other.getFieldName().isEmpty()) {
        fieldName_ = other.fieldName_;
        onChanged();
      }
      if (!other.getFieldValue().isEmpty()) {
        fieldValue_ = other.fieldValue_;
        onChanged();
      }
      if (other.getLevel() != 0) {
        setLevel(other.getLevel());
      }
      if (other.getValidated() != false) {
        setValidated(other.getValidated());
      }
      if (other.hasCreatedDate()) {
        mergeCreatedDate(other.getCreatedDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      VerifiedField parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (VerifiedField) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private Object tenantId_ = "";
    /**
     * <code>string tenantId = 2;</code>
     * @return The tenantId.
     */
    public String getTenantId() {
      Object ref = tenantId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string tenantId = 2;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenantId = 2;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tenantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tenantId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      
      tenantId_ = getDefaultInstance().getTenantId();
      onChanged();
      return this;
    }
    /**
     * <code>string tenantId = 2;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tenantId_ = value;
      onChanged();
      return this;
    }

    private Object personId_ = "";
    /**
     * <code>string personId = 3;</code>
     * @return The personId.
     */
    public String getPersonId() {
      Object ref = personId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        personId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string personId = 3;</code>
     * @return The bytes for personId.
     */
    public com.google.protobuf.ByteString
        getPersonIdBytes() {
      Object ref = personId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        personId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string personId = 3;</code>
     * @param value The personId to set.
     * @return This builder for chaining.
     */
    public Builder setPersonId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      personId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string personId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPersonId() {
      
      personId_ = getDefaultInstance().getPersonId();
      onChanged();
      return this;
    }
    /**
     * <code>string personId = 3;</code>
     * @param value The bytes for personId to set.
     * @return This builder for chaining.
     */
    public Builder setPersonIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      personId_ = value;
      onChanged();
      return this;
    }

    private Object fieldName_ = "";
    /**
     * <code>string fieldName = 4;</code>
     * @return The fieldName.
     */
    public String getFieldName() {
      Object ref = fieldName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fieldName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string fieldName = 4;</code>
     * @return The bytes for fieldName.
     */
    public com.google.protobuf.ByteString
        getFieldNameBytes() {
      Object ref = fieldName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fieldName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fieldName = 4;</code>
     * @param value The fieldName to set.
     * @return This builder for chaining.
     */
    public Builder setFieldName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fieldName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fieldName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFieldName() {
      
      fieldName_ = getDefaultInstance().getFieldName();
      onChanged();
      return this;
    }
    /**
     * <code>string fieldName = 4;</code>
     * @param value The bytes for fieldName to set.
     * @return This builder for chaining.
     */
    public Builder setFieldNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fieldName_ = value;
      onChanged();
      return this;
    }

    private Object fieldValue_ = "";
    /**
     * <code>string fieldValue = 5;</code>
     * @return The fieldValue.
     */
    public String getFieldValue() {
      Object ref = fieldValue_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fieldValue_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string fieldValue = 5;</code>
     * @return The bytes for fieldValue.
     */
    public com.google.protobuf.ByteString
        getFieldValueBytes() {
      Object ref = fieldValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fieldValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fieldValue = 5;</code>
     * @param value The fieldValue to set.
     * @return This builder for chaining.
     */
    public Builder setFieldValue(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fieldValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fieldValue = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFieldValue() {
      
      fieldValue_ = getDefaultInstance().getFieldValue();
      onChanged();
      return this;
    }
    /**
     * <code>string fieldValue = 5;</code>
     * @param value The bytes for fieldValue to set.
     * @return This builder for chaining.
     */
    public Builder setFieldValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fieldValue_ = value;
      onChanged();
      return this;
    }

    private int level_ ;
    /**
     * <code>int32 level = 6;</code>
     * @return The level.
     */
    @Override
    public int getLevel() {
      return level_;
    }
    /**
     * <code>int32 level = 6;</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(int value) {
      
      level_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 level = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      
      level_ = 0;
      onChanged();
      return this;
    }

    private boolean validated_ ;
    /**
     * <code>bool validated = 7;</code>
     * @return The validated.
     */
    @Override
    public boolean getValidated() {
      return validated_;
    }
    /**
     * <code>bool validated = 7;</code>
     * @param value The validated to set.
     * @return This builder for chaining.
     */
    public Builder setValidated(boolean value) {
      
      validated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool validated = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidated() {
      
      validated_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp createdDate = 8;</code>
     * @return Whether the createdDate field is set.
     */
    public boolean hasCreatedDate() {
      return createdDateBuilder_ != null || createdDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 8;</code>
     * @return The createdDate.
     */
    public com.google.protobuf.Timestamp getCreatedDate() {
      if (createdDateBuilder_ == null) {
        return createdDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdDate_;
      } else {
        return createdDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 8;</code>
     */
    public Builder setCreatedDate(com.google.protobuf.Timestamp value) {
      if (createdDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdDate_ = value;
        onChanged();
      } else {
        createdDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 8;</code>
     */
    public Builder setCreatedDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdDateBuilder_ == null) {
        createdDate_ = builderForValue.build();
        onChanged();
      } else {
        createdDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 8;</code>
     */
    public Builder mergeCreatedDate(com.google.protobuf.Timestamp value) {
      if (createdDateBuilder_ == null) {
        if (createdDate_ != null) {
          createdDate_ =
            com.google.protobuf.Timestamp.newBuilder(createdDate_).mergeFrom(value).buildPartial();
        } else {
          createdDate_ = value;
        }
        onChanged();
      } else {
        createdDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 8;</code>
     */
    public Builder clearCreatedDate() {
      if (createdDateBuilder_ == null) {
        createdDate_ = null;
        onChanged();
      } else {
        createdDate_ = null;
        createdDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 8;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedDateBuilder() {
      
      onChanged();
      return getCreatedDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedDateOrBuilder() {
      if (createdDateBuilder_ != null) {
        return createdDateBuilder_.getMessageOrBuilder();
      } else {
        return createdDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp createdDate = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedDateFieldBuilder() {
      if (createdDateBuilder_ == null) {
        createdDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedDate(),
                getParentForChildren(),
                isClean());
        createdDate_ = null;
      }
      return createdDateBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:services.VerifiedField)
  }

  // @@protoc_insertion_point(class_scope:services.VerifiedField)
  private static final VerifiedField DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new VerifiedField();
  }

  public static VerifiedField getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerifiedField>
      PARSER = new com.google.protobuf.AbstractParser<VerifiedField>() {
    @Override
    public VerifiedField parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VerifiedField(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VerifiedField> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VerifiedField> getParserForType() {
    return PARSER;
  }

  @Override
  public VerifiedField getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

